import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { isCategoryPublic } from "@/lib/categories";
import { ProductCard } from "@/components/product-card";

async function findCategory(slug: string) { return prisma.category.findUnique({ where: { slug }, include: { image: true, children: { where: { archivedAt: null, isVisible: true }, include: { image: true }, orderBy: { displayOrder: "asc" } } } }); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const category = await findCategory((await params).slug); return category && await isCategoryPublic(category) ? { title: category.name, description: category.description, alternates: { canonical: `/categories/${category.slug}` } } : {}; }
export default async function CategoryPage({ params }: { params: Promise<{ slug: string }> }) { const category = await findCategory((await params).slug); if (!category || !(await isCategoryPublic(category))) notFound(); const products = await prisma.product.findMany({ where: { categoryId: category.id, status: "ACTIVE", archivedAt: null }, include: { images: { include: { media: true }, orderBy: { position: "asc" }, take: 1 } }, orderBy: { createdAt: "desc" }, take: 8 }); return <><section className="category-hero">{category.image && <Image src={`/api/media/${category.image.id}`} alt={category.name} fill unoptimized priority sizes="100vw" />}<div className="category-hero-shade" /><div className="container"><p className="eyebrow">Curated collection</p><h1>{category.name}</h1><p>{category.description || `Explore the latest ${category.name.toLowerCase()} edit.`}</p></div></section><section className="container section"><div className="section-head"><div><p className="eyebrow">Explore further</p><h2 className="section-title">{category.children.length ? "Shop the collection" : "The latest edit"}</h2></div><Link className="text-link" href={`/shop?category=${category.slug}`}>View all <ArrowRight size={14} /></Link></div>{category.children.length ? <div className="public-subcategories">{category.children.map((child) => <Link href={`/categories/${child.slug}`} key={child.id}><div className="subcategory-art">{child.image ? <Image src={`/api/media/${child.image.id}`} alt="" fill unoptimized sizes="400px" /> : <span>{child.name.charAt(0)}</span>}</div><h2>{child.name}</h2><p>{child.description || "Discover the edit"}</p><span className="text-link">Explore <ArrowRight size={14} /></span></Link>)}</div> : products.length ? <div className="product-grid">{products.map((product) => <ProductCard key={product.id} name={product.name} meta={category.name} price={`₹${((product.salePricePaise ?? product.regularPricePaise) / 100).toLocaleString("en-IN")}`} href={`/products/${product.slug}`} imageUrl={product.images[0] ? `/api/media/${product.images[0].media.id}` : undefined} />)}</div> : <div className="category-empty"><p>We’re preparing this collection with care.</p><Link href="/shop" className="button button-dark">Continue exploring</Link></div>}</section></>; }
