import { z } from "zod";
import type { OrderStatus, Prisma } from "@prisma/client";
import { prisma } from "./prisma";
import { ApiError } from "./api-error";
import { canTransition, orderInclude } from "./orders";
import { enqueueEmail } from "./email";

export const trackingSchema = z.object({ fulfillmentMethod: z.enum(["THIRD_PARTY", "SELF_DELIVERY"]).default("THIRD_PARTY"), courierName: z.string().trim().max(100).nullish().transform((v) => v || null), trackingNumber: z.string().trim().max(120).nullish().transform((v) => v || null), trackingUrl: z.union([z.string().trim().url().refine((value) => /^https?:\/\//i.test(value), "Use an HTTP or HTTPS tracking URL."), z.literal(""), z.null()]).optional().transform((v) => v || null), internalNotes: z.string().trim().max(4000).nullish().transform((v) => v || null) });
export const customerStateSchema = z.object({ isActive: z.boolean() });
export function csvCell(value: unknown) { const text = String(value ?? "").replaceAll('"', '""'); const safe = /^[=+@-]/.test(text) ? `'${text}` : text; return `"${safe}"`; }
export function ordersCsv(rows: { orderNumber: string; customer: string; email: string; status: string; totalPaise: number; createdAt: Date }[]) { return [["Order", "Customer", "Email", "Status", "Total INR", "Created UTC"], ...rows.map((row) => [row.orderNumber, row.customer, row.email, row.status, (row.totalPaise / 100).toFixed(2), row.createdAt.toISOString()])].map((row) => row.map(csvCell).join(",")).join("\n"); }
export function revenueTotal(orders: { totalPaise: number; paymentStatus: string; status: string }[]) { return orders.filter((order) => order.paymentStatus === "PAID" && order.status !== "CANCELLED").reduce((sum, order) => sum + order.totalPaise, 0); }
const orderStatuses: OrderStatus[] = ["PENDING_PAYMENT", "PLACED", "CONFIRMED", "PACKED", "SHIPPED", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELLED"];
export function adminOrderWhere(params: URLSearchParams): Prisma.OrderWhereInput { const q = params.get("q")?.trim(); const status = params.get("status") as OrderStatus | null; return { ...(q ? { OR: [{ orderNumber: { contains: q } }, { trackingNumber: { contains: q } }, { user: { OR: [{ name: { contains: q } }, { email: { contains: q } }, { mobile: { contains: q } }] } }] } : {}), ...(status && orderStatuses.includes(status) ? { status } : {}) }; }

export async function updateOrderOperations(actorId: number, orderId: number, raw: unknown) { const input = trackingSchema.parse(raw); const order = await prisma.order.findUnique({ where: { id: orderId } }); if (!order) throw new ApiError(404, "ORDER_NOT_FOUND", "Order not found."); const details = input.fulfillmentMethod === "SELF_DELIVERY" ? { ...input, courierName: null, trackingNumber: null, trackingUrl: null } : input; return prisma.$transaction(async (tx) => { const updated = await tx.order.update({ where: { id: orderId }, data: details, include: orderInclude }); await tx.adminAudit.create({ data: { actorId, action: "ORDER_DETAILS_UPDATED", entityType: "ORDER", entityId: String(orderId), summary: `${details.fulfillmentMethod === "SELF_DELIVERY" ? "Self delivery" : `Courier ${details.courierName ?? "not set"}; tracking ${details.trackingNumber ?? "not set"}`}.` } }); return updated; }); }
export async function progressOrder(actorId: number, orderId: number, status: OrderStatus) { return prisma.$transaction(async (tx) => { const current = await tx.order.findUnique({ where: { id: orderId }, include: { user: true } }); if (!current) throw new ApiError(404, "ORDER_NOT_FOUND", "Order not found."); if (current.status === status) return tx.order.findUniqueOrThrow({ where: { id: orderId }, include: orderInclude }); if (!canTransition(current.status, status)) throw new ApiError(409, "INVALID_STATUS_TRANSITION", `Cannot move an order from ${current.status} to ${status}.`); if (status === "SHIPPED" && current.fulfillmentMethod === "THIRD_PARTY" && (!current.courierName || !current.trackingNumber)) throw new ApiError(409, "TRACKING_REQUIRED", "Add courier and tracking details before marking this order shipped."); const updated = await tx.order.update({ where: { id: orderId }, data: { status, ...(status === "SHIPPED" ? { shippedAt: new Date() } : {}), ...(status === "DELIVERED" ? { deliveredAt: new Date(), paymentStatus: "PAID" } : {}), history: { create: { status, note: `${current.fulfillmentMethod === "SELF_DELIVERY" ? "Self delivery" : "Third-party delivery"} · Updated by store staff.` } } }, include: orderInclude }); if (status === "DELIVERED") for (const item of updated.items) await tx.product.update({ where: { id: item.productId }, data: { deliveredSalesCount: { increment: item.quantity } } }); await tx.adminAudit.create({ data: { actorId, action: "ORDER_STATUS_UPDATED", entityType: "ORDER", entityId: String(orderId), summary: `${current.status} → ${status}` } }); const kind = status === "SHIPPED" ? "SHIPPED" : status === "DELIVERED" ? "DELIVERED" : "ORDER_STATUS"; await enqueueEmail(tx, `order-status:${orderId}:${status}`, current.user.email, kind, { name: current.user.name, orderNumber: current.orderNumber, status, courier: current.fulfillmentMethod === "SELF_DELIVERY" ? "Yoranzify delivery" : current.courierName || undefined, trackingNumber: current.trackingNumber || undefined, url: `${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/account/orders/${orderId}` }); return updated; }); }
export async function setCustomerActive(actorId: number, customerId: number, raw: unknown) { const { isActive } = customerStateSchema.parse(raw); const customer = await prisma.user.findFirst({ where: { id: customerId, role: "CUSTOMER" } }); if (!customer) throw new ApiError(404, "CUSTOMER_NOT_FOUND", "Customer not found."); return prisma.$transaction(async (tx) => { const updated = await tx.user.update({ where: { id: customerId }, data: { isActive }, select: { id: true, name: true, email: true, mobile: true, isActive: true } }); if (!isActive) await tx.session.deleteMany({ where: { userId: customerId } }); await tx.adminAudit.create({ data: { actorId, action: isActive ? "CUSTOMER_ENABLED" : "CUSTOMER_DISABLED", entityType: "USER", entityId: String(customerId), summary: customer.email } }); return updated; }); }

export async function dashboardData() { const now = new Date(); const today = new Date(now); today.setHours(0, 0, 0, 0); const month = new Date(now.getFullYear(), now.getMonth(), 1); const since = new Date(now); since.setDate(since.getDate() - 6); since.setHours(0, 0, 0, 0); const [orders, recentOrders, monthOrders, customerCount, productCount, lowStock, outOfStock, statusGroups, topItems] = await Promise.all([prisma.order.findMany({ where: { paymentStatus: "PAID", status: { not: "CANCELLED" } }, select: { totalPaise: true, createdAt: true, paymentStatus: true, status: true } }), prisma.order.findMany({ include: { user: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 6 }), prisma.order.count({ where: { createdAt: { gte: month } } }), prisma.user.count({ where: { role: "CUSTOMER" } }), prisma.product.count({ where: { archivedAt: null } }), prisma.productVariant.count({ where: { isActive: true, stockQuantity: { gt: 0, lte: 5 } } }), prisma.productVariant.count({ where: { isActive: true, stockQuantity: 0 } }), prisma.order.groupBy({ by: ["status"], _count: true }), prisma.orderItem.groupBy({ by: ["productId", "productName"], where: { order: { paymentStatus: "PAID", status: { not: "CANCELLED" } } }, _sum: { quantity: true, lineTotalPaise: true }, orderBy: { _sum: { quantity: "desc" } }, take: 5 })]); const daily = Array.from({ length: 7 }, (_, i) => { const date = new Date(since); date.setDate(since.getDate() + i); const key = date.toISOString().slice(0, 10); return { date: key, revenuePaise: orders.filter((order) => order.createdAt.toISOString().slice(0, 10) === key).reduce((sum, order) => sum + order.totalPaise, 0) }; }); return { totalRevenuePaise: revenueTotal(orders), todayRevenuePaise: orders.filter((order) => order.createdAt >= today).reduce((sum, order) => sum + order.totalPaise, 0), monthOrders, customerCount, productCount, lowStock, outOfStock, daily, statusGroups, topItems, recentOrders };
}
