import { prisma } from "./prisma";

export const ANALYTICS_PERIODS = [7, 30, 90, 365] as const;
export function analyticsPeriod(value?: string) { const days = Number(value); return ANALYTICS_PERIODS.includes(days as (typeof ANALYTICS_PERIODS)[number]) ? days : 30; }
const dateKey = (date: Date) => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(date);
export function percentageChange(current: number, previous: number) { if (!previous) return current ? 100 : 0; return Math.round((current - previous) / previous * 1000) / 10; }

export async function analyticsData(days: number) {
  const end = new Date(); const start = new Date(end); start.setDate(start.getDate() - days + 1); start.setHours(0, 0, 0, 0); const previousStart = new Date(start); previousStart.setDate(previousStart.getDate() - days);
  const orderSelect = { id: true, userId: true, status: true, paymentStatus: true, paymentMethod: true, merchandiseSubtotalPaise: true, automaticDiscountPaise: true, couponDiscountPaise: true, shippingPaise: true, platformFeePaise: true, taxPaise: true, totalPaise: true, createdAt: true, items: { select: { productId: true, productName: true, quantity: true, lineTotalPaise: true, product: { select: { category: { select: { id: true, name: true } } } } } } } as const;
  const [orders, previousOrders, newCustomers, reviews, inventoryValue] = await Promise.all([
    prisma.order.findMany({ where: { createdAt: { gte: start } }, select: orderSelect, orderBy: { createdAt: "asc" } }),
    prisma.order.findMany({ where: { createdAt: { gte: previousStart, lt: start } }, select: { status: true, paymentStatus: true, totalPaise: true } }),
    prisma.user.count({ where: { role: "CUSTOMER", createdAt: { gte: start } } }),
    prisma.review.aggregate({ where: { status: "APPROVED", createdAt: { gte: start } }, _avg: { rating: true }, _count: true }),
    prisma.productVariant.findMany({ where: { isActive: true, product: { archivedAt: null } }, select: { stockQuantity: true, priceOverridePaise: true, product: { select: { regularPricePaise: true, salePricePaise: true } } } })
  ]);
  const isPaid = (order: { paymentStatus: string; status: string }) => order.paymentStatus === "PAID" && order.status !== "CANCELLED";
  const isPlaced = (order: { status: string }) => !["PENDING_PAYMENT", "CANCELLED"].includes(order.status);
  const paid = orders.filter(isPaid); const placed = orders.filter(isPlaced); const previousPaid = previousOrders.filter(isPaid); const previousPlaced = previousOrders.filter(isPlaced);
  const sum = <T,>(items: T[], pick: (item: T) => number) => items.reduce((total, item) => total + pick(item), 0);
  const revenuePaise = sum(paid, (order) => order.totalPaise); const previousRevenuePaise = sum(previousPaid, (order) => order.totalPaise);
  const byDay = new Map<string, { revenuePaise: number; orders: number }>(); for (let i = 0; i < days; i++) { const day = new Date(start); day.setDate(start.getDate() + i); byDay.set(dateKey(day), { revenuePaise: 0, orders: 0 }); } for (const order of paid) { const current = byDay.get(dateKey(order.createdAt)); if (current) { current.revenuePaise += order.totalPaise; current.orders++; } }
  const products = new Map<number, { name: string; units: number; revenuePaise: number }>(); const categories = new Map<number, { name: string; units: number; revenuePaise: number }>(); for (const order of paid) for (const item of order.items) { const product = products.get(item.productId) ?? { name: item.productName, units: 0, revenuePaise: 0 }; product.units += item.quantity; product.revenuePaise += item.lineTotalPaise; products.set(item.productId, product); const categoryInfo = item.product.category; const category = categories.get(categoryInfo.id) ?? { name: categoryInfo.name, units: 0, revenuePaise: 0 }; category.units += item.quantity; category.revenuePaise += item.lineTotalPaise; categories.set(categoryInfo.id, category); }
  const paymentMix = (["COD", "RAZORPAY"] as const).map((method) => ({ method, count: placed.filter((order) => order.paymentMethod === method).length, revenuePaise: sum(paid.filter((order) => order.paymentMethod === method), (order) => order.totalPaise) }));
  const statuses = ["PENDING_PAYMENT", "PLACED", "CONFIRMED", "PACKED", "SHIPPED", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELLED"].map((status) => ({ status, count: orders.filter((order) => order.status === status).length }));
  const userOrders = new Map<number, number>(); for (const order of placed) userOrders.set(order.userId, (userOrders.get(order.userId) ?? 0) + 1);
  return { days, start, end, revenuePaise, revenueChange: percentageChange(revenuePaise, previousRevenuePaise), placedOrders: placed.length, orderChange: percentageChange(placed.length, previousPlaced.length), averageOrderPaise: paid.length ? Math.round(revenuePaise / paid.length) : 0, unitsSold: [...products.values()].reduce((total, product) => total + product.units, 0), discountsPaise: sum(paid, (order) => order.automaticDiscountPaise + order.couponDiscountPaise), shippingPaise: sum(paid, (order) => order.shippingPaise), platformFeesPaise: sum(paid, (order) => order.platformFeePaise), taxIncludedPaise: sum(paid, (order) => order.taxPaise), newCustomers, repeatCustomers: [...userOrders.values()].filter((count) => count > 1).length, cancelledOrders: orders.filter((order) => order.status === "CANCELLED").length, deliveredOrders: orders.filter((order) => order.status === "DELIVERED").length, approvedReviews: reviews._count, averageRating: reviews._avg.rating ?? 0, inventoryRetailValuePaise: sum(inventoryValue, (variant) => variant.stockQuantity * (variant.priceOverridePaise ?? variant.product.salePricePaise ?? variant.product.regularPricePaise)), daily: [...byDay].map(([date, values]) => ({ date, ...values })), topProducts: [...products.values()].sort((a, b) => b.revenuePaise - a.revenuePaise).slice(0, 8), topCategories: [...categories.values()].sort((a, b) => b.revenuePaise - a.revenuePaise).slice(0, 6), paymentMix, statuses };
}
