import nodemailer from "nodemailer";
import type { Prisma } from "@prisma/client";
import { prisma } from "./prisma";

type MailKind = "WELCOME" | "PASSWORD_RESET" | "ORDER_PLACED" | "ADMIN_NEW_ORDER" | "PAYMENT_CONFIRMED" | "ORDER_STATUS" | "SHIPPED" | "DELIVERED" | "CANCELLED";
const DISABLED_CUSTOMER_ORDER_EMAILS = new Set<MailKind>(["ORDER_PLACED", "PAYMENT_CONFIRMED", "ORDER_STATUS", "SHIPPED", "DELIVERED", "CANCELLED"]);
type MailItem = { name: string; variant?: string; quantity: number; amountPaise: number };
type MailData = { name: string; orderNumber?: string; status?: string; url?: string; trackingNumber?: string; courier?: string; customerEmail?: string; customerMobile?: string; address?: string; paymentMethod?: string; subtotalPaise?: number; discountPaise?: number; shippingPaise?: number; platformFeePaise?: number; totalPaise?: number; items?: MailItem[] };
type OrderMailSource = { id: number; orderNumber: string; paymentMethod: string; addressFullName: string; addressMobile: string; addressLine1: string; addressLine2: string | null; addressCity: string; addressState: string; addressPostalCode: string; merchandiseSubtotalPaise: number; automaticDiscountPaise: number; couponDiscountPaise: number; shippingPaise: number; platformFeePaise: number; totalPaise: number; items: { productName: string; colorName: string; sizeName: string; quantity: number; lineTotalPaise: number }[] };
const escape = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
const money = (value = 0) => `₹${(value / 100).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const safeUrl = (value?: string) => value && /^https?:\/\//.test(value) ? escape(value) : "";
export function orderMailData(order: OrderMailSource, customer: { name: string; email: string; mobile?: string }): MailData { return { name: customer.name, orderNumber: order.orderNumber, customerEmail: customer.email, customerMobile: customer.mobile || order.addressMobile, address: [order.addressLine1, order.addressLine2, `${order.addressCity}, ${order.addressState} ${order.addressPostalCode}`].filter(Boolean).join(", "), paymentMethod: order.paymentMethod === "COD" ? "Cash on Delivery" : "Paid online", subtotalPaise: order.merchandiseSubtotalPaise, discountPaise: order.automaticDiscountPaise + order.couponDiscountPaise, shippingPaise: order.shippingPaise, platformFeePaise: order.platformFeePaise, totalPaise: order.totalPaise, items: order.items.map((item) => ({ name: item.productName, variant: `${item.colorName} / ${item.sizeName}`, quantity: item.quantity, amountPaise: item.lineTotalPaise })) }; }

function orderEmail(kind: "ORDER_PLACED" | "PAYMENT_CONFIRMED" | "ADMIN_NEW_ORDER", data: MailData) {
  const admin = kind === "ADMIN_NEW_ORDER"; const order = escape(data.orderNumber || ""); const name = escape(data.name); const url = safeUrl(data.url); const title = admin ? "New order received" : kind === "PAYMENT_CONFIRMED" ? "Payment confirmed" : "Your order is confirmed"; const intro = admin ? `${name} placed a new order on Yoranzify.` : kind === "PAYMENT_CONFIRMED" ? `Hi ${name}, your payment was successful and order ${order} is confirmed.` : `Hi ${name}, thank you for shopping with Yoranzify. We have confirmed order ${order} and will begin preparing it.`;
  const rows = (data.items ?? []).map((item) => `<tr><td style="padding:14px 0;border-bottom:1px solid #e5e0d8"><b>${escape(item.name)}</b>${item.variant ? `<br><span style="color:#777;font-size:12px">${escape(item.variant)}</span>` : ""}</td><td style="padding:14px 10px;border-bottom:1px solid #e5e0d8;text-align:center">${item.quantity}</td><td style="padding:14px 0;border-bottom:1px solid #e5e0d8;text-align:right">${money(item.amountPaise)}</td></tr>`).join("");
  const details = admin ? `<div style="background:#f5f1e9;padding:18px;margin:22px 0"><b>Customer</b><p style="line-height:1.6;margin:7px 0 0">${name}<br>${escape(data.customerEmail || "")} · ${escape(data.customerMobile || "")}<br>${escape(data.address || "")}</p></div>` : "";
  const html = `<div style="background:#f3efe7;padding:30px 12px;font-family:Arial,sans-serif;color:#171814"><div style="max-width:640px;margin:auto;background:#fff;border:1px solid #ded8cd"><div style="background:#171814;color:#fff;padding:28px 34px"><div style="font-family:Georgia,serif;font-size:29px;letter-spacing:4px">YORANZIFY</div><div style="font-size:10px;letter-spacing:3px;margin-top:7px;color:#d7cfc3">WEAR YOUR STORY</div></div><div style="padding:34px"><p style="font-size:11px;font-weight:bold;letter-spacing:2px;color:#9a6248">ORDER ${order}</p><h1 style="font-family:Georgia,serif;font-size:38px;font-weight:normal;margin:10px 0 18px">${title}</h1><p style="font-size:16px;line-height:1.7">${intro}</p>${details}<table style="width:100%;border-collapse:collapse;margin:24px 0"><thead><tr><th style="text-align:left;padding-bottom:10px">Item</th><th style="text-align:center;padding-bottom:10px">Qty</th><th style="text-align:right;padding-bottom:10px">Amount</th></tr></thead><tbody>${rows}</tbody></table><table style="width:100%;max-width:330px;margin-left:auto;line-height:1.9"><tr><td>Subtotal</td><td style="text-align:right">${money(data.subtotalPaise)}</td></tr><tr><td>Discounts</td><td style="text-align:right">−${money(data.discountPaise)}</td></tr><tr><td>Shipping</td><td style="text-align:right">${money(data.shippingPaise)}</td></tr>${data.platformFeePaise ? `<tr><td>Platform fee</td><td style="text-align:right">${money(data.platformFeePaise)}</td></tr>` : ""}<tr><td style="border-top:2px solid #171814;padding-top:8px"><b>Total</b></td><td style="border-top:2px solid #171814;padding-top:8px;text-align:right"><b>${money(data.totalPaise)}</b></td></tr><tr><td>Payment</td><td style="text-align:right">${escape(data.paymentMethod || "")}</td></tr></table>${url ? `<p style="margin-top:30px"><a href="${url}" style="display:inline-block;background:#9a6248;color:#fff;padding:14px 22px;text-decoration:none;font-weight:bold">${admin ? "Manage order" : "View your order"}</a></p>` : ""}<p style="color:#777;font-size:12px;line-height:1.6;margin-top:32px">Need help? Reply to this email and our team will assist you.</p></div></div></div>`;
  const subject = admin ? `New order ${order} · ${money(data.totalPaise)}` : kind === "PAYMENT_CONFIRMED" ? `Payment confirmed · Order ${order}` : `Order confirmed · ${order}`; const text = `${title}\n\n${intro}\n\nTotal: ${money(data.totalPaise)}\nPayment: ${data.paymentMethod || ""}${url ? `\n\n${url}` : ""}`;
  return { subject, text, html };
}

export function renderEmail(kind: MailKind, data: MailData) {
  if (kind === "ORDER_PLACED" || kind === "PAYMENT_CONFIRMED" || kind === "ADMIN_NEW_ORDER") return orderEmail(kind, data);
  const name = escape(data.name); const order = escape(data.orderNumber || ""); const status = escape((data.status || "").replaceAll("_", " ").toLowerCase()); const url = safeUrl(data.url); const copy: Record<Exclude<MailKind, "ORDER_PLACED" | "PAYMENT_CONFIRMED" | "ADMIN_NEW_ORDER">, [string,string]> = { WELCOME: ["Welcome to Yoranzify", `Welcome, ${name}. Your wardrobe account is ready.`], PASSWORD_RESET: ["Reset your Yoranzify password", `Hello ${name}, use the secure link below to reset your password.`], ORDER_STATUS: [`Order ${order} update`, `Your order is now ${status}.`], SHIPPED: [`Order ${order} is on its way`, `Your order has shipped with ${escape(data.courier || "our courier")}. Tracking: ${escape(data.trackingNumber || "pending")}.`], DELIVERED: [`Order ${order} delivered`, "Your Yoranzify order has been delivered."], CANCELLED: [`Order ${order} cancelled`, `Order ${order} has been cancelled.`] }; const [subject, text] = copy[kind]; const action = url ? `<p><a href="${url}" style="background:#20231d;color:#fff;padding:12px 18px;text-decoration:none">View details</a></p>` : ""; return { subject, text: `${text}${url ? ` ${url}` : ""}`, html: `<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#20231d"><h1 style="font-family:Georgia,serif">Yoranzify</h1><p>${text}</p>${action}<p style="color:#777">Quiet form. Bold presence.</p></div>` };
}
export async function enqueueEmail(db: Prisma.TransactionClient | typeof prisma, dedupeKey: string, recipient: string, kind: MailKind, data: MailData) { if (DISABLED_CUSTOMER_ORDER_EMAILS.has(kind)) return null; const rendered = renderEmail(kind, data); return db.emailOutbox.upsert({ where: { dedupeKey }, create: { dedupeKey, recipient, template: kind, ...rendered }, update: { recipient, template: kind, ...rendered } }); }
export function retryDelay(attempt: number) { return Math.min(24 * 60, 2 ** Math.max(0, attempt - 1) * 5) * 60_000; }
function transport() { if (process.env.SMTP_HOST === "json") return nodemailer.createTransport({ jsonTransport: true }); if (!process.env.SMTP_HOST) throw new Error("SMTP is not configured"); return nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT || 587), secure: Number(process.env.SMTP_PORT) === 465, auth: process.env.SMTP_USER ? { user: process.env.SMTP_USER, pass: process.env.SMTP_PASSWORD } : undefined }); }
export async function deliverOutbox(limit = 25) { const rows = await prisma.emailOutbox.findMany({ where: { status: { in: ["PENDING", "FAILED"] }, nextAttemptAt: { lte: new Date() }, attempts: { lt: 8 } }, orderBy: { createdAt: "asc" }, take: limit }); let sent = 0; for (const row of rows) { const claimed = await prisma.emailOutbox.updateMany({ where: { id: row.id, status: row.status }, data: { status: "SENDING", attempts: { increment: 1 } } }); if (!claimed.count) continue; try { await transport().sendMail({ from: process.env.SMTP_FROM || "Yoranzify <no-reply@yoranzify.com>", to: row.recipient, subject: row.subject, html: row.html, text: row.text }); await prisma.emailOutbox.update({ where: { id: row.id }, data: { status: "SENT", sentAt: new Date(), lastError: null } }); sent++; } catch (error) { const message = error instanceof Error ? error.message.slice(0, 500) : "Delivery failed"; await prisma.emailOutbox.update({ where: { id: row.id }, data: { status: "FAILED", lastError: message, nextAttemptAt: new Date(Date.now() + retryDelay(row.attempts + 1)) } }); } } return { processed: rows.length, sent, failed: rows.length - sent }; }
