import nodemailer from "nodemailer";
import type { Prisma } from "@prisma/client";
import { prisma } from "./prisma";

type MailKind = "WELCOME" | "PASSWORD_RESET" | "ORDER_PLACED" | "PAYMENT_CONFIRMED" | "ORDER_STATUS" | "SHIPPED" | "DELIVERED" | "CANCELLED";
type MailData = { name: string; orderNumber?: string; status?: string; url?: string; trackingNumber?: string; courier?: string };
const escape = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
export function renderEmail(kind: MailKind, data: MailData) { const name = escape(data.name); const order = escape(data.orderNumber || ""); const status = escape((data.status || "").replaceAll("_", " ").toLowerCase()); const url = data.url && /^https?:\/\//.test(data.url) ? escape(data.url) : ""; const copy: Record<MailKind, [string,string]> = { WELCOME: ["Welcome to Yoranzify", `Welcome, ${name}. Your wardrobe account is ready.`], PASSWORD_RESET: ["Reset your Yoranzify password", `Hello ${name}, use the secure link below to reset your password.`], ORDER_PLACED: [`Order ${order} received`, `Thank you, ${name}. We have received order ${order}.`], PAYMENT_CONFIRMED: [`Payment confirmed for ${order}`, `Your payment for order ${order} is confirmed.`], ORDER_STATUS: [`Order ${order} update`, `Your order is now ${status}.`], SHIPPED: [`Order ${order} is on its way`, `Your order has shipped with ${escape(data.courier || "our courier")}. Tracking: ${escape(data.trackingNumber || "pending")}.`], DELIVERED: [`Order ${order} delivered`, `Your Yoranzify order has been delivered.`], CANCELLED: [`Order ${order} cancelled`, `Order ${order} has been cancelled.`] }; const [subject, text] = copy[kind]; const action = url ? `<p><a href="${url}" style="background:#20231d;color:#fff;padding:12px 18px;text-decoration:none">View details</a></p>` : ""; return { subject, text: `${text}${url ? ` ${url}` : ""}`, html: `<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#20231d"><h1 style="font-family:Georgia,serif">Yoranzify</h1><p>${text}</p>${action}<p style="color:#777">Quiet form. Bold presence.</p></div>` }; }
export async function enqueueEmail(db: Prisma.TransactionClient | typeof prisma, dedupeKey: string, recipient: string, kind: MailKind, data: MailData) { const rendered = renderEmail(kind, data); return db.emailOutbox.upsert({ where: { dedupeKey }, create: { dedupeKey, recipient, template: kind, ...rendered }, update: {} }); }
export function retryDelay(attempt: number) { return Math.min(24 * 60, 2 ** Math.max(0, attempt - 1) * 5) * 60_000; }
function transport() { if (process.env.SMTP_HOST === "json") return nodemailer.createTransport({ jsonTransport: true }); if (!process.env.SMTP_HOST) throw new Error("SMTP is not configured"); return nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT || 587), secure: Number(process.env.SMTP_PORT) === 465, auth: process.env.SMTP_USER ? { user: process.env.SMTP_USER, pass: process.env.SMTP_PASSWORD } : undefined }); }
export async function deliverOutbox(limit = 25) { const rows = await prisma.emailOutbox.findMany({ where: { status: { in: ["PENDING", "FAILED"] }, nextAttemptAt: { lte: new Date() }, attempts: { lt: 8 } }, orderBy: { createdAt: "asc" }, take: limit }); let sent = 0; for (const row of rows) { const claimed = await prisma.emailOutbox.updateMany({ where: { id: row.id, status: row.status }, data: { status: "SENDING", attempts: { increment: 1 } } }); if (!claimed.count) continue; try { await transport().sendMail({ from: process.env.SMTP_FROM || "Yoranzify <no-reply@yoranzify.com>", to: row.recipient, subject: row.subject, html: row.html, text: row.text }); await prisma.emailOutbox.update({ where: { id: row.id }, data: { status: "SENT", sentAt: new Date(), lastError: null } }); sent++; } catch (error) { const message = error instanceof Error ? error.message.slice(0, 500) : "Delivery failed"; await prisma.emailOutbox.update({ where: { id: row.id }, data: { status: "FAILED", lastError: message, nextAttemptAt: new Date(Date.now() + retryDelay(row.attempts + 1)) } }); } } return { processed: rows.length, sent, failed: rows.length - sent }; }
