import { randomBytes } from "node:crypto";
import { z } from "zod";
import type { OrderStatus, Prisma } from "@prisma/client";
import { prisma } from "./prisma";
import { ApiError } from "./api-error";
import { effectivePrice } from "./products";
import { bestPromotion, categoryShippingPaise, validateCoupon, type CouponRule, type PromotionRule } from "./pricing";
import { isActiveOffer } from "./promotions";
import { enqueueEmail } from "./email";

export const checkoutSchema = z.object({ addressId: z.number().int().positive(), paymentMethod: z.enum(["COD", "RAZORPAY"]), idempotencyKey: z.string().min(16).max(64) });
export const orderInclude = { items: true, payments: { orderBy: { createdAt: "desc" as const } }, history: { orderBy: { createdAt: "asc" as const } } } satisfies Prisma.OrderInclude;
export const CANCELLABLE_STATUSES: OrderStatus[] = ["PENDING_PAYMENT", "PLACED", "CONFIRMED"];
export function canTransition(from: OrderStatus, to: OrderStatus) { const next: Partial<Record<OrderStatus, OrderStatus[]>> = { PLACED: ["CONFIRMED", "CANCELLED"], CONFIRMED: ["PACKED", "CANCELLED"], PACKED: ["SHIPPED"], SHIPPED: ["OUT_FOR_DELIVERY"], OUT_FOR_DELIVERY: ["DELIVERED"] }; return next[from]?.includes(to) ?? false; }
export function taxIncludedPaise(amountPaise: number, gstPercent: number) { return gstPercent <= 0 ? 0 : Math.round(amountPaise * gstPercent / (100 + gstPercent)); }
const number = () => `YRZ-${new Date().toISOString().slice(2, 10).replaceAll("-", "")}-${randomBytes(3).toString("hex").toUpperCase()}`;

async function orderPricing(tx: Prisma.TransactionClient, userId: number) {
  const cart = await tx.cart.findUnique({ where: { userId }, include: { items: { include: { variant: { include: { color: true, size: true, product: { include: { category: true } } } } } }, coupon: { include: { customers: true, usages: { where: { status: { in: ["RESERVED", "REDEEMED"] } } } } } } });
  if (!cart?.items.length) throw new ApiError(409, "EMPTY_CART", "Your bag is empty.");
  const now = new Date(); const offers = await tx.promotion.findMany({ where: { enabled: true }, include: { products: true, categories: true } });
  const promotions: PromotionRule[] = offers.filter((offer) => isActiveOffer(offer, now)).map((offer) => ({ ...offer, productIds: offer.products.map((item) => item.productId), categoryIds: offer.categories.map((item) => item.categoryId) }));
  const lines = cart.items.map((item) => { const { variant } = item; const product = variant.product; if (!variant.isActive || product.status !== "ACTIVE" || product.archivedAt || !product.category.isVisible || product.category.archivedAt || variant.stockQuantity < item.quantity) throw new ApiError(409, "STOCK_CHANGED", `${product.name} is no longer available in that quantity.`); const unitPricePaise = effectivePrice(product.regularPricePaise, product.salePricePaise, variant.priceOverridePaise); const gross = unitPricePaise * item.quantity; const automatic = bestPromotion(gross, product.id, product.categoryId, promotions); return { cartItemId: item.id, productId: product.id, variantId: variant.id, productName: product.name, productSlug: product.slug, sku: variant.sku, colorName: variant.color.name, sizeName: variant.size.name, quantity: item.quantity, unitPricePaise, automaticDiscountPaise: automatic?.discountPaise ?? 0, gstPercent: Number(product.gstPercent) }; });
  const merchandiseSubtotalPaise = lines.reduce((sum, line) => sum + line.unitPricePaise * line.quantity, 0); const automaticDiscountPaise = lines.reduce((sum, line) => sum + line.automaticDiscountPaise, 0); const afterPromotions = merchandiseSubtotalPaise - automaticDiscountPaise;
  let couponDiscountPaise = 0; if (cart.coupon) { if (!isActiveOffer(cart.coupon, now)) throw new ApiError(409, "COUPON_CHANGED", "Your coupon is no longer active. Review your bag and try again."); const rule: CouponRule = { ...cart.coupon, name: cart.coupon.code, customerIds: cart.coupon.customers.map((item) => item.userId), totalUsage: cart.coupon.usages.length, userUsage: cart.coupon.usages.filter((item) => item.userId === userId).length }; couponDiscountPaise = validateCoupon(rule, afterPromotions, userId); }
  const settings = await tx.siteSetting.findUnique({ where: { id: 1 } }); const discountedSubtotal = afterPromotions - couponDiscountPaise; const shippingPaise = categoryShippingPaise(lines.map((line) => ({ categoryId: line.productId ? cart.items.find((item) => item.id === line.cartItemId)!.variant.product.categoryId : 0, subtotalPaise: line.unitPricePaise * line.quantity - line.automaticDiscountPaise, shippingChargePaise: cart.items.find((item) => item.id === line.cartItemId)!.variant.product.category.shippingChargePaise, freeShippingAbovePaise: cart.items.find((item) => item.id === line.cartItemId)!.variant.product.category.freeShippingAbovePaise })), settings?.shippingChargePaise ?? 9900, settings?.freeShippingAbovePaise ?? 199900); const platformFeePaise = discountedSubtotal > 0 ? settings?.platformFeePaise ?? 0 : 0; const totalPaise = discountedSubtotal + shippingPaise + platformFeePaise;
  const couponShares = lines.map((line) => afterPromotions ? Math.floor(couponDiscountPaise * (line.unitPricePaise * line.quantity - line.automaticDiscountPaise) / afterPromotions) : 0); if (couponShares.length) couponShares[couponShares.length - 1] += couponDiscountPaise - couponShares.reduce((a, b) => a + b, 0);
  return { cart, lines: lines.map((line, index) => { const lineAfterDiscount = line.unitPricePaise * line.quantity - line.automaticDiscountPaise - couponShares[index]; return { ...line, couponDiscountPaise: couponShares[index], taxPaise: taxIncludedPaise(lineAfterDiscount, line.gstPercent), lineTotalPaise: lineAfterDiscount }; }), merchandiseSubtotalPaise, automaticDiscountPaise, couponDiscountPaise, shippingPaise, platformFeePaise, totalPaise };
}

export async function checkoutPreview(userId: number) { return prisma.$transaction(async (tx) => { const priced = await orderPricing(tx, userId); return { items: priced.lines, subtotalPaise: priced.merchandiseSubtotalPaise, automaticDiscountPaise: priced.automaticDiscountPaise, couponCode: priced.cart.coupon?.code ?? null, couponDiscountPaise: priced.couponDiscountPaise, shippingPaise: priced.shippingPaise, platformFeePaise: priced.platformFeePaise, totalPaise: priced.totalPaise }; }); }

async function createOrderAttempt(userId: number, raw: unknown, gateway?: { orderId: string; expiresAt: Date }) { const input = checkoutSchema.parse(raw); if (input.paymentMethod === "RAZORPAY" && !gateway) throw new ApiError(503, "PAYMENT_SETUP_FAILED", "Online payment could not be prepared."); const existing = await prisma.order.findUnique({ where: { idempotencyKey: input.idempotencyKey }, include: orderInclude }); if (existing) { if (existing.userId !== userId) throw new ApiError(409, "DUPLICATE_SUBMISSION", "This checkout request was already used."); return existing; }
  return prisma.$transaction(async (tx) => { const address = await tx.address.findFirst({ where: { id: input.addressId, userId } }); if (!address) throw new ApiError(404, "ADDRESS_NOT_FOUND", "Choose a valid delivery address."); const settings = await tx.siteSetting.findUnique({ where: { id: 1 } }); if (input.paymentMethod === "COD" && !settings?.codEnabled) throw new ApiError(409, "COD_DISABLED", "Cash on delivery is currently unavailable."); const priced = await orderPricing(tx, userId);
    const customer = await tx.user.findUniqueOrThrow({ where: { id: userId }, select: { name: true, email: true } });
    for (const line of priced.lines) { const changed = await tx.productVariant.updateMany({ where: { id: line.variantId, stockQuantity: { gte: line.quantity } }, data: { stockQuantity: { decrement: line.quantity } } }); if (changed.count !== 1) throw new ApiError(409, "STOCK_CHANGED", `${line.productName} sold out while you were checking out.`); }
    const online = input.paymentMethod === "RAZORPAY"; const order = await tx.order.create({ data: { orderNumber: number(), idempotencyKey: input.idempotencyKey, userId, paymentMethod: input.paymentMethod, status: online ? "PENDING_PAYMENT" : "PLACED", addressFullName: address.fullName, addressMobile: address.mobile, addressLine1: address.line1, addressLine2: address.line2, addressLandmark: address.landmark, addressCity: address.city, addressState: address.state, addressPostalCode: address.postalCode, addressCountry: address.country, merchandiseSubtotalPaise: priced.merchandiseSubtotalPaise, automaticDiscountPaise: priced.automaticDiscountPaise, couponCode: priced.cart.coupon?.code, couponDiscountPaise: priced.couponDiscountPaise, shippingPaise: priced.shippingPaise, taxPaise: priced.lines.reduce((sum, item) => sum + item.taxPaise, 0), totalPaise: priced.totalPaise, items: { create: priced.lines.map((line) => ({ productId: line.productId, variantId: line.variantId, productName: line.productName, productSlug: line.productSlug, sku: line.sku, colorName: line.colorName, sizeName: line.sizeName, quantity: line.quantity, unitPricePaise: line.unitPricePaise, automaticDiscountPaise: line.automaticDiscountPaise, couponDiscountPaise: line.couponDiscountPaise, taxPaise: line.taxPaise, lineTotalPaise: line.lineTotalPaise })) }, history: { create: { status: online ? "PENDING_PAYMENT" : "PLACED", note: online ? "Awaiting verified Razorpay payment." : "Order placed with Cash on Delivery." } }, reservations: { create: priced.lines.map((line) => ({ variantId: line.variantId, quantity: line.quantity })) }, ...(online ? { payments: { create: { gatewayOrderId: gateway!.orderId, amountPaise: priced.totalPaise, expiresAt: gateway!.expiresAt } } } : {}) }, include: orderInclude });
    await tx.order.update({ where: { id: order.id }, data: { platformFeePaise: priced.platformFeePaise } });
    for (const line of priced.lines) { const variant = await tx.productVariant.findUniqueOrThrow({ where: { id: line.variantId }, select: { stockQuantity: true } }); await tx.inventoryMovement.create({ data: { variantId: line.variantId, delta: -line.quantity, balance: variant.stockQuantity, reason: "SALE", note: `Order ${order.orderNumber}`, actorId: userId } }); }
    if (priced.cart.couponId) await tx.couponUsage.create({ data: { couponId: priced.cart.couponId, userId, status: online ? "RESERVED" : "REDEEMED", orderId: order.id } }); await tx.cartItem.deleteMany({ where: { cartId: priced.cart.id } }); await tx.cart.update({ where: { id: priced.cart.id }, data: { couponId: null } }); if (!online) await enqueueEmail(tx, `order-placed:${order.id}`, customer.email, "ORDER_PLACED", { name: customer.name, orderNumber: order.orderNumber, url: `${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/account/orders/${order.id}` }); return order;
  }, { isolationLevel: "Serializable", timeout: 15000 });
}

async function retryCreate(userId: number, raw: unknown, gateway?: { orderId: string; expiresAt: Date }) { for (let attempt = 0; ; attempt++) { try { return await createOrderAttempt(userId, raw, gateway); } catch (error) { if ((error as { code?: string }).code !== "P2034" || attempt >= 2) throw error; } } }
export async function createCodOrder(userId: number, raw: unknown) { const input = checkoutSchema.parse(raw); if (input.paymentMethod !== "COD") throw new ApiError(400, "INVALID_PAYMENT_METHOD", "Choose Cash on Delivery."); return retryCreate(userId, input); }
export async function createOnlineOrder(userId: number, raw: unknown, gateway: { orderId: string; expiresAt: Date }) { const input = checkoutSchema.parse(raw); if (input.paymentMethod !== "RAZORPAY") throw new ApiError(400, "INVALID_PAYMENT_METHOD", "Choose Razorpay."); return retryCreate(userId, input, gateway); }

export async function cancelOrder(userId: number, orderId: number, admin = false) { return prisma.$transaction(async (tx) => { const order = await tx.order.findFirst({ where: { id: orderId, ...(admin ? {} : { userId }) }, include: { reservations: true } }); if (!order) throw new ApiError(404, "ORDER_NOT_FOUND", "Order not found."); if (order.status === "CANCELLED") return tx.order.findUniqueOrThrow({ where: { id: orderId }, include: orderInclude }); if (!CANCELLABLE_STATUSES.includes(order.status)) throw new ApiError(409, "ORDER_NOT_CANCELLABLE", "This order can no longer be cancelled online."); for (const reservation of order.reservations.filter((item) => item.status === "CONSUMED")) { const released = await tx.inventoryReservation.updateMany({ where: { id: reservation.id, status: "CONSUMED" }, data: { status: "RELEASED", releasedAt: new Date() } }); if (released.count) { const variant = await tx.productVariant.update({ where: { id: reservation.variantId }, data: { stockQuantity: { increment: reservation.quantity } } }); await tx.inventoryMovement.create({ data: { variantId: reservation.variantId, delta: reservation.quantity, balance: variant.stockQuantity, reason: "CANCELLATION", note: `Cancelled ${order.orderNumber}`, actorId: userId } }); } } await tx.couponUsage.updateMany({ where: { orderId, status: "REDEEMED" }, data: { status: "RELEASED" } }); return tx.order.update({ where: { id: orderId }, data: { status: "CANCELLED", cancelledAt: new Date(), history: { create: { status: "CANCELLED", note: "Order cancelled and stock restored." } } }, include: orderInclude }); }, { isolationLevel: "Serializable" }); }

export async function updateOrderStatus(orderId: number, status: OrderStatus) { return prisma.$transaction(async (tx) => { const current = await tx.order.findUnique({ where: { id: orderId } }); if (!current) throw new ApiError(404, "ORDER_NOT_FOUND", "Order not found."); if (!canTransition(current.status, status)) throw new ApiError(409, "INVALID_STATUS_TRANSITION", `Cannot move an order from ${current.status} to ${status}.`); return tx.order.update({ where: { id: orderId }, data: { status, history: { create: { status } }, ...(status === "DELIVERED" ? { paymentStatus: "PAID" } : {}) }, include: orderInclude }); }); }
