import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { prisma } from "./prisma";
import { ApiError } from "./api-error";
import { cancelOrder, checkoutPreview, createOnlineOrder, orderInclude } from "./orders";
import { enqueueEmail } from "./email";

const RESERVATION_MINUTES = 15;
export const razorpayConfigured = () => Boolean(process.env.RAZORPAY_KEY_ID && process.env.RAZORPAY_KEY_SECRET);
export const razorpayMockEnabled = () => process.env.NODE_ENV !== "production" && (process.env.RAZORPAY_MOCK === "true" || !razorpayConfigured());
function safeEqualHex(expected: string, received: string) { if (!/^[a-f0-9]+$/i.test(received) || expected.length !== received.length) return false; return timingSafeEqual(Buffer.from(expected, "hex"), Buffer.from(received, "hex")); }
export function verifyCheckoutSignature(gatewayOrderId: string, paymentId: string, signature: string, secret: string) { return safeEqualHex(createHmac("sha256", secret).update(`${gatewayOrderId}|${paymentId}`).digest("hex"), signature); }
export function verifyWebhookSignature(rawBody: string, signature: string, secret: string) { return safeEqualHex(createHmac("sha256", secret).update(rawBody).digest("hex"), signature); }

async function createGatewayOrder(amount: number, receipt: string) { if (razorpayMockEnabled()) return { id: `order_mock_${randomBytes(8).toString("hex")}`, amount, currency: "INR" }; if (!razorpayConfigured()) throw new ApiError(503, "RAZORPAY_NOT_CONFIGURED", "Online payment is currently unavailable."); const credentials = Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${process.env.RAZORPAY_KEY_SECRET}`).toString("base64"); let response: Response; try { response = await fetch("https://api.razorpay.com/v1/orders", { method: "POST", headers: { Authorization: `Basic ${credentials}`, "Content-Type": "application/json" }, body: JSON.stringify({ amount, currency: "INR", receipt }) }); } catch { throw new ApiError(502, "PAYMENT_NETWORK_ERROR", "Could not reach Razorpay. No payment was started; please retry."); } if (!response.ok) throw new ApiError(502, "PAYMENT_GATEWAY_ERROR", "Razorpay could not prepare this payment. Please retry."); const body = await response.json() as { id?: string; amount?: number; currency?: string }; if (!body.id || body.amount !== amount || body.currency !== "INR") throw new ApiError(502, "PAYMENT_GATEWAY_MISMATCH", "Razorpay returned an invalid order response."); return { id: body.id, amount, currency: "INR" }; }

export async function initiateRazorpayPayment(userId: number, raw: unknown) { const input = raw as { idempotencyKey?: string }; if (input.idempotencyKey) { const existing = await prisma.order.findUnique({ where: { idempotencyKey: input.idempotencyKey }, include: orderInclude }); if (existing && existing.userId === userId && existing.payments[0]) return presentPayment(existing); } const preview = await checkoutPreview(userId); const gateway = await createGatewayOrder(preview.totalPaise, `yrz_${String(input.idempotencyKey ?? "").slice(0, 30)}`); const expiresAt = new Date(Date.now() + RESERVATION_MINUTES * 60_000); const order = await createOnlineOrder(userId, raw, { orderId: gateway.id, expiresAt }); if (order.totalPaise !== gateway.amount) { await expirePayment(order.payments[0].id, "AMOUNT_CHANGED", "Cart total changed during payment setup."); throw new ApiError(409, "CHECKOUT_CHANGED", "Your total changed. Review your order and try again."); } return presentPayment(order); }
function presentPayment(order: Awaited<ReturnType<typeof createOnlineOrder>>) { const payment = order.payments[0]; return { orderId: order.id, orderNumber: order.orderNumber, gatewayOrderId: payment.gatewayOrderId, amountPaise: payment.amountPaise, currency: payment.currency, keyId: razorpayMockEnabled() ? "rzp_test_mock" : process.env.RAZORPAY_KEY_ID, mock: razorpayMockEnabled(), expiresAt: payment.expiresAt }; }

export async function captureVerifiedPayment(gatewayOrderId: string, gatewayPaymentId: string, amountPaise?: number) { return prisma.$transaction(async (tx) => { const payment = await tx.payment.findUnique({ where: { gatewayOrderId }, include: { order: { include: { user: true } } } }); if (!payment) throw new ApiError(404, "PAYMENT_NOT_FOUND", "Payment attempt not found."); if (amountPaise != null && amountPaise !== payment.amountPaise) throw new ApiError(409, "PAYMENT_AMOUNT_MISMATCH", "Payment amount does not match the order."); if (payment.status === "CAPTURED") return tx.order.findUniqueOrThrow({ where: { id: payment.orderId }, include: orderInclude }); if (["FAILED", "EXPIRED", "REFUNDED"].includes(payment.status)) throw new ApiError(409, "PAYMENT_ALREADY_CLOSED", "This payment attempt is already closed."); await tx.payment.update({ where: { id: payment.id }, data: { status: "CAPTURED", gatewayPaymentId } }); await tx.couponUsage.updateMany({ where: { orderId: payment.orderId, status: "RESERVED" }, data: { status: "REDEEMED" } }); const order = await tx.order.update({ where: { id: payment.orderId }, data: { status: "PLACED", paymentStatus: "PAID", history: { create: { status: "PLACED", note: "Payment captured and verified by Razorpay." } } }, include: orderInclude }); await enqueueEmail(tx, `payment-confirmed:${order.id}`, payment.order.user.email, "PAYMENT_CONFIRMED", { name: payment.order.user.name, orderNumber: order.orderNumber, url: `${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/account/orders/${order.id}` }); return order; }); }

export async function verifyCheckoutPayment(userId: number, input: { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string }) { const payment = await prisma.payment.findUnique({ where: { gatewayOrderId: input.razorpay_order_id }, include: { order: true } }); if (!payment || payment.order.userId !== userId) throw new ApiError(404, "PAYMENT_NOT_FOUND", "Payment attempt not found."); const secret = process.env.RAZORPAY_KEY_SECRET; if (!secret || !verifyCheckoutSignature(payment.gatewayOrderId, input.razorpay_payment_id, input.razorpay_signature, secret)) throw new ApiError(400, "INVALID_PAYMENT_SIGNATURE", "Payment verification failed."); const credentials = Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${secret}`).toString("base64"); let response: Response; try { response = await fetch(`https://api.razorpay.com/v1/payments/${encodeURIComponent(input.razorpay_payment_id)}`, { headers: { Authorization: `Basic ${credentials}` } }); } catch { throw new ApiError(502, "PAYMENT_STATUS_UNAVAILABLE", "Payment was received but confirmation is delayed. Refresh your order status shortly."); } if (!response.ok) throw new ApiError(502, "PAYMENT_STATUS_UNAVAILABLE", "Payment confirmation is delayed. Refresh your order status shortly."); const gateway = await response.json() as { status?: string; order_id?: string; amount?: number }; if (gateway.status !== "captured" || gateway.order_id !== payment.gatewayOrderId || gateway.amount !== payment.amountPaise) throw new ApiError(409, "PAYMENT_NOT_CAPTURED", "Payment is not captured yet. Your order will update after Razorpay confirms it."); return captureVerifiedPayment(payment.gatewayOrderId, input.razorpay_payment_id, gateway.amount);
}

export async function expirePayment(paymentId: number, code = "EXPIRED", description = "Payment window expired.") { const payment = await prisma.payment.findUnique({ where: { id: paymentId }, include: { order: true } }); if (!payment || ["CAPTURED", "EXPIRED", "FAILED", "REFUNDED"].includes(payment.status)) return; await prisma.payment.update({ where: { id: payment.id }, data: { status: code === "EXPIRED" ? "EXPIRED" : "FAILED", failureCode: code, failureDescription: description } }); await cancelOrder(payment.order.userId, payment.orderId, true); }
export async function failGatewayPayment(gatewayOrderId: string, paymentId: string | null, code: string, description: string) { const payment = await prisma.payment.findUnique({ where: { gatewayOrderId }, include: { order: true } }); if (!payment || payment.status === "CAPTURED") return; await prisma.payment.update({ where: { id: payment.id }, data: { status: "FAILED", gatewayPaymentId: paymentId, failureCode: code.slice(0, 100), failureDescription: description.slice(0, 500) } }); await cancelOrder(payment.order.userId, payment.orderId, true); }
export async function releaseExpiredPayments() { const expired = await prisma.payment.findMany({ where: { status: { in: ["INITIATED", "AUTHORIZED"] }, expiresAt: { lte: new Date() } }, select: { id: true } }); for (const payment of expired) await expirePayment(payment.id); return expired.length; }

type WebhookPayload = { event?: string; payload?: { payment?: { entity?: { id?: string; order_id?: string; amount?: number; status?: string; error_code?: string; error_description?: string } }; order?: { entity?: { id?: string; amount_paid?: number } } } };
export async function processWebhook(eventId: string, rawBody: string, signature: string) { const secret = process.env.RAZORPAY_WEBHOOK_SECRET; if (!secret || !verifyWebhookSignature(rawBody, signature, secret)) throw new ApiError(400, "INVALID_WEBHOOK_SIGNATURE", "Invalid webhook signature."); const payload = JSON.parse(rawBody) as WebhookPayload; const eventType = payload.event ?? "unknown"; const payloadHash = createHash("sha256").update(rawBody).digest("hex"); try { await prisma.webhookEvent.create({ data: { gatewayEventId: eventId, eventType, payloadHash } }); } catch (error) { if ((error as { code?: string }).code === "P2002") return { duplicate: true }; throw error; } const entity = payload.payload?.payment?.entity; if ((eventType === "payment.captured" || eventType === "order.paid") && entity?.order_id && entity.id) await captureVerifiedPayment(entity.order_id, entity.id, entity.amount); else if (eventType === "payment.failed" && entity?.order_id) await failGatewayPayment(entity.order_id, entity.id ?? null, entity.error_code ?? "FAILED", entity.error_description ?? "Payment failed."); await prisma.webhookEvent.update({ where: { gatewayEventId: eventId }, data: { processedAt: new Date() } }); return { duplicate: false }; }
