import { Prisma } from "@prisma/client";
import { z } from "zod";
import { prisma } from "./prisma";
import { ApiError } from "./api-error";

const indianMobile = z.string().transform((value) => { const digits = value.replace(/\D/g, ""); return digits.length === 12 && digits.startsWith("91") ? digits.slice(2) : digits; }).pipe(z.string().regex(/^[6-9]\d{9}$/, "Enter a valid Indian mobile number"));
export const profileSchema = z.object({ name: z.string().trim().min(2, "Enter your full name").max(100), email: z.string().trim().toLowerCase().pipe(z.email("Enter a valid email address")), mobile: indianMobile });
export const addressSchema = z.object({ fullName: z.string().trim().min(2).max(100), mobile: indianMobile, line1: z.string().trim().min(5, "Enter a complete address").max(180), line2: z.string().trim().max(180).nullish().transform((value) => value ?? ""), landmark: z.string().trim().max(120).nullish().transform((value) => value ?? ""), city: z.string().trim().min(2).max(100), state: z.string().trim().min(2).max(100), postalCode: z.string().trim().regex(/^[1-9]\d{5}$/, "Enter a valid 6-digit Indian PIN code"), country: z.string().trim().max(80).default("India").refine((value) => value.toLowerCase() === "india", "Only Indian addresses are currently supported"), type: z.enum(["HOME", "WORK", "OTHER"]), isDefaultShipping: z.boolean().default(false) });
export async function retryAddressWrite<T>(operation: () => Promise<T>) { for (let attempt = 0; ; attempt++) { try { return await operation(); } catch (error) { if (!(error instanceof Prisma.PrismaClientKnownRequestError) || error.code !== "P2034" || attempt >= 2) throw error; } } }

export async function updateProfile(userId: number, raw: unknown) { const input = profileSchema.parse(raw); try { return await prisma.user.update({ where: { id: userId }, data: input, select: { id: true, name: true, email: true, mobile: true, role: true } }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw new ApiError(409, "PROFILE_CONFLICT", "That email or mobile number is already used by another account."); throw error; } }
export async function listAddresses(userId: number) { return prisma.address.findMany({ where: { userId }, orderBy: [{ isDefaultShipping: "desc" }, { createdAt: "asc" }] }); }
export async function createAddress(userId: number, raw: unknown) { const input = addressSchema.parse(raw); return prisma.$transaction(async (tx) => { const count = await tx.address.count({ where: { userId } }); const makeDefault = input.isDefaultShipping || count === 0; if (makeDefault && count > 0) await tx.address.updateMany({ where: { userId }, data: { isDefaultShipping: false } }); return tx.address.create({ data: { ...input, line2: input.line2 || null, landmark: input.landmark || null, country: "India", isDefaultShipping: makeDefault, userId } }); }); }
export async function updateAddress(userId: number, addressId: number, raw: unknown) { const input = addressSchema.parse(raw); return prisma.$transaction(async (tx) => { const existing = await tx.address.findFirst({ where: { id: addressId, userId } }); if (!existing) throw new ApiError(404, "ADDRESS_NOT_FOUND", "Address not found."); if (input.isDefaultShipping) await tx.address.updateMany({ where: { userId, id: { not: addressId } }, data: { isDefaultShipping: false } }); let keepDefault = input.isDefaultShipping; if (existing.isDefaultShipping && !input.isDefaultShipping) { const replacement = await tx.address.findFirst({ where: { userId, id: { not: addressId } }, orderBy: { createdAt: "asc" } }); if (replacement) await tx.address.update({ where: { id: replacement.id }, data: { isDefaultShipping: true } }); else keepDefault = true; } return tx.address.update({ where: { id: addressId }, data: { ...input, line2: input.line2 || null, landmark: input.landmark || null, country: "India", isDefaultShipping: keepDefault } }); }); }
export async function deleteAddress(userId: number, addressId: number) { return prisma.$transaction(async (tx) => { const existing = await tx.address.findFirst({ where: { id: addressId, userId } }); if (!existing) throw new ApiError(404, "ADDRESS_NOT_FOUND", "Address not found."); await tx.address.delete({ where: { id: addressId } }); if (existing.isDefaultShipping) { const replacement = await tx.address.findFirst({ where: { userId }, orderBy: { createdAt: "asc" } }); if (replacement) await tx.address.update({ where: { id: replacement.id }, data: { isDefaultShipping: true } }); } }); }
export async function setDefaultAddress(userId: number, addressId: number) { return prisma.$transaction(async (tx) => { const existing = await tx.address.findFirst({ where: { id: addressId, userId } }); if (!existing) throw new ApiError(404, "ADDRESS_NOT_FOUND", "Address not found."); await tx.address.updateMany({ where: { userId }, data: { isDefaultShipping: false } }); return tx.address.update({ where: { id: addressId }, data: { isDefaultShipping: true } }); }); }
