import { expect, test } from "@playwright/test";

test("store shell and interactive search load", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("h1").first()).toBeVisible();
  await page.waitForLoadState("networkidle");
  const searchButton = page.getByRole("button", { name: "Search", exact: true });
  await searchButton.click();
  await expect(searchButton).toHaveAttribute("aria-expanded", "true");
  await expect(page.getByRole("textbox", { name: "Search products" })).toBeFocused();
});

test("admin shell loads", async ({ page }) => {
  await page.goto("/admin");
  await expect(page).toHaveURL(/\/login\?next=%2Fadmin/);
  await page.getByLabel("Email address").fill("admin@yoranzify.local");
  await page.getByLabel("Password", { exact: true }).fill("Yoranzify123!");
  await page.getByRole("button", { name: /Sign in/ }).click();
  await expect(page).toHaveURL(/\/admin$/);
  await expect(page.getByRole("heading", { name: "Store at a glance." })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Revenue · last 7 days" })).toBeVisible();
});

test("customer can register, stay signed in, and sign out", async ({ page }, testInfo) => {
  const email = `customer-${testInfo.project.name}-${Date.now()}@example.com`;
  const mobile = `${testInfo.project.name === "mobile" ? "9" : "8"}${testInfo.workerIndex}${String(Date.now()).slice(-8)}`;
  await page.goto("/register");
  await page.getByLabel("Full name").fill("Aanya Customer");
  await page.getByLabel("Email address").fill(email);
  await page.getByLabel("Mobile number").fill(mobile);
  await page.getByLabel("Password", { exact: true }).fill("Wardrobe9!");
  await page.getByLabel("Confirm password").fill("Wardrobe9!");
  await page.getByRole("button", { name: /Create account/ }).click();
  await expect(page).toHaveURL(/\/account$/);
  await page.reload();
  await expect(page.getByRole("heading", { name: /Hello, Aanya/ })).toBeVisible();
  await page.getByLabel("Profile full name").fill("Aanya Edited");
  await page.getByRole("button", { name: "Save profile" }).click();
  await expect(page.getByRole("status")).toContainText("Profile updated successfully");
  await page.goto("/account/addresses");
  await page.getByRole("button", { name: "Add address" }).click();
  await page.getByLabel("Address full name").fill("Aanya Edited");
  await page.getByLabel("Address mobile number").fill(mobile);
  await page.getByLabel("Address line 1").fill("12 Studio Road");
  await page.getByLabel("City").fill("Ahmedabad");
  await page.getByLabel("State").fill("Gujarat");
  await page.getByLabel("PIN code").fill("380015");
  await page.getByRole("button", { name: "Save address" }).click();
  const homeAddress = page.locator(".address-card").filter({ hasText: "12 Studio Road" });
  await expect(homeAddress).toContainText("Default");
  await page.getByRole("button", { name: "Add address" }).click();
  await page.getByLabel("Address full name").fill("Aanya Office");
  await page.getByLabel("Address mobile number").fill(mobile);
  await page.getByLabel("Address line 1").fill("88 Fashion Avenue");
  await page.getByLabel("City").fill("Ahmedabad");
  await page.getByLabel("State").fill("Gujarat");
  await page.getByLabel("PIN code").fill("380009");
  await page.getByLabel("Address type").selectOption("WORK");
  await page.getByRole("button", { name: "Save address" }).click();
  const workAddress = page.locator(".address-card").filter({ hasText: "88 Fashion Avenue" });
  await workAddress.getByRole("button", { name: "Make default" }).click();
  await expect(workAddress).toContainText("Default");
  await workAddress.getByRole("button", { name: "Edit address for Aanya Office" }).click();
  await page.getByLabel("Landmark").fill("Design District");
  await page.getByRole("button", { name: "Save address" }).click();
  await expect(workAddress).toContainText("Design District");
  page.on("dialog", (dialog) => dialog.accept());
  await workAddress.getByRole("button", { name: "Delete address for Aanya Office" }).click();
  await expect(workAddress).toHaveCount(0);
  await expect(homeAddress).toContainText("Default");
  expect(await page.evaluate(async () => (await fetch("/api/admin/settings")).status)).toBe(403);
  await page.goto("/admin");
  await expect(page).toHaveURL(/\/unauthorized$/);
  await page.goto("/account");
  await page.getByRole("button", { name: "Sign out" }).click();
  await expect(page).toHaveURL(/\/$/);
  await page.goto("/account");
  await expect(page).toHaveURL(/\/login/);
});

test("password reset revokes the old password", async ({ page }, testInfo) => {
  const stamp = `${testInfo.project.name}-${Date.now()}`;
  const email = `reset-${stamp}@example.com`;
  const mobile = `${testInfo.project.name === "mobile" ? "7" : "6"}${testInfo.workerIndex}${String(Date.now()).slice(-8)}`;
  await page.goto("/register");
  await page.getByLabel("Full name").fill("Reset Customer");
  await page.getByLabel("Email address").fill(email);
  await page.getByLabel("Mobile number").fill(mobile);
  await page.getByLabel("Password", { exact: true }).fill("Wardrobe9!");
  await page.getByLabel("Confirm password").fill("Wardrobe9!");
  await page.getByRole("button", { name: /Create account/ }).click();
  await expect(page).toHaveURL(/\/account$/);
  await page.getByRole("button", { name: "Sign out" }).click();
  await page.goto("/forgot-password");
  await page.getByLabel("Email address").fill(email);
  await page.getByRole("button", { name: /Send reset link/ }).click();
  await page.getByRole("link", { name: /Development only/ }).click();
  await page.getByLabel("Password", { exact: true }).fill("NewWardrobe8!");
  await page.getByLabel("Confirm password").fill("NewWardrobe8!");
  await page.getByRole("button", { name: /Update password/ }).click();
  await expect(page).toHaveURL(/\/login\?password=updated/);
  await page.getByLabel("Email address").fill(email);
  await page.getByLabel("Password", { exact: true }).fill("Wardrobe9!");
  await page.getByRole("button", { name: /Sign in/ }).click();
  await expect(page.getByRole("status")).toContainText("incorrect");
  await page.getByLabel("Password", { exact: true }).fill("NewWardrobe8!");
  await page.getByRole("button", { name: /Sign in/ }).click();
  await expect(page).toHaveURL(/\/account$/);
});

test("admin manages store settings and optimized logo", async ({ page }, testInfo) => {
  await page.goto("/login?next=%2Fadmin%2Fsettings");
  await page.getByLabel("Email address").fill("admin@yoranzify.local");
  await page.getByLabel("Password", { exact: true }).fill("Yoranzify123!");
  await page.getByRole("button", { name: /Sign in/ }).click();
  await expect(page).toHaveURL(/\/admin\/settings$/);
  await expect(page.getByRole("heading", { name: "Settings" })).toBeVisible();
  if (testInfo.project.name === "mobile") return;
  await page.locator('input[type="file"]').first().setInputFiles("public/images/yoranzify-hero.png");
  await expect(page.getByAltText("Store logo preview")).toBeVisible();
  await page.getByLabel("Free shipping above (₹)").fill("2500");
  await page.getByRole("button", { name: /Save settings/ }).click();
  await expect(page.getByText("Store settings saved successfully.")).toBeVisible();
  await page.goto("/");
  await expect(page.getByText("Complimentary shipping on orders over ₹2,500")).toBeVisible();
  await expect(page.getByRole("img", { name: "Yoranzify" }).first()).toBeVisible();
  await page.goto("/admin/settings");
  await page.getByLabel("Free shipping above (₹)").fill("1999");
  await page.getByRole("button", { name: "Remove store logo" }).click();
  await page.getByRole("button", { name: /Save settings/ }).click();
  await expect(page.getByText("Store settings saved successfully.")).toBeVisible();
});

test("admin builds, publishes, hides, and archives a category tree", async ({ page }, testInfo) => {
  const suffix = `${testInfo.project.name}-${Date.now()}`;
  const rootName = `Editorial ${suffix}`;
  const childName = `Linen ${suffix}`;
  await page.goto("/login?next=%2Fadmin%2Fcategories");
  await page.getByLabel("Email address").fill("admin@yoranzify.local");
  await page.getByLabel("Password", { exact: true }).fill("Yoranzify123!");
  await page.getByRole("button", { name: /Sign in/ }).click();
  await expect(page).toHaveURL(/\/admin\/categories$/);
  await page.getByRole("button", { name: "Add category" }).click();
  await page.getByLabel("Name").fill(rootName);
  await page.getByLabel("Description").fill("A considered edit for everyday dressing.");
  await page.getByRole("button", { name: "Save category" }).click();
  const rootRow = page.locator(".category-admin-row").filter({ hasText: rootName });
  await expect(rootRow).toBeVisible();
  await rootRow.getByRole("button", { name: `Add child to ${rootName}` }).click();
  await page.getByLabel("Name").fill(childName);
  await page.getByRole("button", { name: "Save category" }).click();
  const childRow = page.locator(".category-admin-row").filter({ hasText: childName });
  await expect(childRow).toBeVisible();
  const rootSlug = rootName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  await page.goto(`/categories/${rootSlug}`);
  await expect(page.getByRole("heading", { name: rootName })).toBeVisible();
  await expect(page.getByRole("heading", { name: childName })).toBeVisible();
  await page.goto("/admin/categories");
  const publishedChildRow = page.locator(".category-admin-row").filter({ hasText: childName });
  await publishedChildRow.getByRole("button", { name: `Hide ${childName}` }).click();
  await expect(publishedChildRow).toContainText("Hidden");
  await page.goto(`/categories/${rootSlug}`);
  await expect(page.getByRole("heading", { name: childName })).toHaveCount(0);
  await page.goto("/admin/categories");
  page.on("dialog", (dialog) => dialog.accept());
  const hiddenChildRow = page.locator(".category-admin-row").filter({ hasText: childName });
  await hiddenChildRow.getByRole("button", { name: `Archive ${childName}` }).click();
  await expect(hiddenChildRow).toHaveClass(/archived/);
  const finalRootRow = page.locator(".category-admin-row").filter({ hasText: rootName });
  await finalRootRow.getByRole("button", { name: `Archive ${rootName}` }).click();
  await expect(finalRootRow).toHaveClass(/archived/);
  await page.goto(`/categories/${rootSlug}`);
  await expect(page.getByRole("heading", { name: "That page slipped away." })).toBeVisible();
});

test("admin creates variant stock and customer selects each size", async ({ page }, testInfo) => {
  const stamp = `${testInfo.project.name}-${Date.now()}`;
  const productName = `Studio Tee ${stamp}`;
  const ref = `TEE-${testInfo.project.name === "mobile" ? "MOB" : "DES"}-${String(Date.now()).slice(-6)}`;
  const skuM = `${ref}-BLK-M`;
  const skuL = `${ref}-BLK-L`;
  await page.goto("/login?next=%2Fadmin%2Fproducts%2Fnew");
  await page.getByLabel("Email address").fill("admin@yoranzify.local");
  await page.getByLabel("Password", { exact: true }).fill("Yoranzify123!");
  await page.getByRole("button", { name: /Sign in/ }).click();
  await expect(page).toHaveURL(/\/admin\/products\/new$/);
  await page.getByLabel("Product name").fill(productName);
  await page.getByLabel("SKU reference").fill(ref);
  await page.getByLabel("Regular price (₹)").fill("1299");
  await page.getByLabel("Sale price (₹)").fill("899");
  await page.getByLabel("Short description").fill("A relaxed everyday essential in soft cotton.");
  await page.getByLabel("Full description").fill("Designed with an easy silhouette and considered finishing.");
  await page.getByLabel("Status").selectOption("ACTIVE");
  await page.getByRole("button", { name: /Media & SEO/ }).click();
  const fileInput = page.locator('.image-add input[type="file"]');
  await fileInput.setInputFiles("public/images/yoranzify-hero.png");
  await expect(page.getByLabel("Alt text image 1")).toBeVisible();
  await page.getByLabel("Alt text image 1").fill("Front campaign view");
  await fileInput.setInputFiles("public/images/yoranzify-hero.png");
  await expect(page.getByLabel("Alt text image 2")).toBeVisible();
  await page.getByLabel("Alt text image 2").fill("Back campaign view");
  await page.getByRole("button", { name: "Move image 2 left" }).click();
  await expect(page.getByLabel("Alt text image 1")).toHaveValue("Back campaign view");
  await page.getByRole("button", { name: /Variants & stock/ }).click();
  await page.getByLabel("Variant 1 SKU").fill(skuM);
  await page.getByLabel("Variant 1 stock").fill("10");
  await page.getByRole("button", { name: "Add variant" }).click();
  const variantRows = page.locator(".variant-row");
  await variantRows.nth(1).locator("select").nth(1).selectOption("L");
  await page.getByLabel("Variant 2 SKU").fill(skuL);
  await page.getByLabel("Variant 2 stock").fill("3");
  await page.getByRole("button", { name: /Save product/ }).click({ force: true });
  await expect(page).toHaveURL(/\/admin\/products$/);
  const listResponse = await page.request.get("/api/admin/products");
  const list = await listResponse.json();
  const created = list.products.find((product: { name: string }) => product.name === productName);
  expect(created).toBeTruthy();
  const couponCode = `EDIT${String(Date.now()).slice(-7)}`;
  await page.goto("/admin/offers");
  await page.getByRole("button", { name: "Promotion", exact: true }).click();
  await page.getByLabel("Name").fill(`Studio promotion ${stamp}`);
  await page.getByLabel("Discount (%)").fill("10");
  await page.getByText(productName, { exact: true }).click();
  await page.getByRole("button", { name: "Save offer" }).click();
  await expect(page.getByText(`Studio promotion ${stamp}`, { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Coupon", exact: true }).click();
  await page.getByLabel("Name").fill(`Customer edit ${stamp}`);
  await page.getByRole("textbox", { name: "Coupon code" }).fill(couponCode);
  await page.getByLabel("Discount (%)").fill("5");
  await page.getByLabel("Minimum spend (₹)").fill("100");
  await page.getByRole("button", { name: "Save offer" }).click();
  await expect(page.getByText(couponCode, { exact: true })).toBeVisible();
  await page.request.post("/api/auth/logout");
  await page.goto(`/products/${created.slug}`);
  await expect(page.getByRole("heading", { name: productName, exact: true })).toBeVisible();
  await page.getByRole("button", { name: "M", exact: true }).click();
  await expect(page.getByText(`10 available · SKU ${skuM}`)).toBeVisible();
  await page.getByRole("button", { name: "L", exact: true }).click();
  await expect(page.getByText(`3 available · SKU ${skuL}`)).toBeVisible();
  await page.getByRole("button", { name: "Add to bag" }).click();
  await expect(page.getByRole("complementary", { name: "Shopping bag" })).toBeVisible();
  await page.getByRole("complementary", { name: "Shopping bag" }).getByRole("button", { name: "Close shopping bag" }).click();
  await page.reload();
  await expect(page.getByRole("button", { name: "Shopping bag with 1 items" })).toBeVisible();
  await page.getByRole("button", { name: "Shopping bag with 1 items" }).click();
  await page.getByRole("link", { name: "View bag" }).click();
  await page.getByRole("button", { name: `Increase ${productName}` }).click();
  await expect(page.getByRole("button", { name: "Shopping bag with 2 items" })).toBeVisible();
  await expect(page.locator(".cart-page-grid").getByText(/Studio promotion/)).toBeVisible();
  await page.getByLabel("Coupon code").fill(couponCode);
  await page.getByRole("button", { name: "Apply" }).click();
  await expect(page.getByText(couponCode, { exact: true })).toBeVisible();
  await expect(page.locator(".cart-page-grid").getByText("Promotions", { exact: true })).toBeVisible();
  const cartEmail = `cart-${stamp}@example.com`;
  const cartMobile = `${testInfo.project.name === "mobile" ? "7" : "6"}${testInfo.workerIndex}${String(Date.now()).slice(-8)}`;
  await page.goto("/register");
  await page.getByLabel("Full name").fill("Cart Customer");
  await page.getByLabel("Email address").fill(cartEmail);
  await page.getByLabel("Mobile number").fill(cartMobile);
  await page.getByLabel("Password", { exact: true }).fill("Wardrobe9!");
  await page.getByLabel("Confirm password").fill("Wardrobe9!");
  await page.getByRole("button", { name: /Create account/ }).click();
  await expect(page).toHaveURL(/\/account$/);
  await page.goto("/cart");
  await expect(page.getByText(`${productName}`).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "Shopping bag with 2 items" })).toBeVisible();
  await page.goto(`/shop?q=${encodeURIComponent(productName)}`);
  await page.getByRole("button", { name: `Add ${productName} to wishlist` }).click();
  await expect(page.getByRole("button", { name: `Remove ${productName} from wishlist` })).toBeVisible();
  await page.goto("/account/wishlist");
  await expect(page.getByRole("heading", { name: productName, exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("heading", { name: productName, exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Move to bag" }).click();
  await expect(page.getByRole("heading", { name: productName, exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Shopping bag with 3 items" })).toBeVisible();
  await page.goto(`/shop?q=${encodeURIComponent(productName)}`);
  await expect(page.getByRole("heading", { name: `Results for “${productName}”` })).toBeVisible();
  await expect(page.getByRole("heading", { name: productName, exact: true })).toBeVisible();
  if (testInfo.project.name === "mobile") await page.getByRole("button", { name: "Filters", exact: true }).click();
  const filters = page.getByRole("complementary", { name: "Product filters" });
  await filters.getByLabel("Category").selectOption(created.category.slug);
  await filters.getByText("Black", { exact: true }).click();
  await filters.getByText("L", { exact: true }).click();
  await filters.getByText("Only show in-stock pieces").click();
  await filters.getByRole("button", { name: "Show pieces" }).click();
  await expect(page).toHaveURL(/category=/);
  await expect(page).toHaveURL(/size=L/);
  await expect(page).toHaveURL(/color=Black/);
  await expect(page.getByRole("heading", { name: productName, exact: true })).toBeVisible();
  await page.goto(`/shop?q=${encodeURIComponent(`missing ${stamp}`)}`);
  await expect(page.getByRole("heading", { name: "No pieces match your edit." })).toBeVisible();
  await page.goBack();
  await expect(page.getByRole("heading", { name: productName, exact: true })).toBeVisible();
  await page.goto("/account/addresses");
  await page.getByRole("button", { name: "Add address" }).click();
  await page.getByLabel("Address full name").fill("Cart Customer");
  await page.getByLabel("Address mobile number").fill(cartMobile);
  await page.getByLabel("Address line 1").fill("42 Checkout Street");
  await page.getByLabel("City").fill("Ahmedabad");
  await page.getByLabel("State").fill("Gujarat");
  await page.getByLabel("PIN code").fill("380015");
  await page.getByRole("button", { name: "Save address" }).click();
  await page.goto("/cart");
  await page.getByRole("link", { name: "Secure checkout" }).click();
  await expect(page.getByRole("heading", { name: "Complete your order." })).toBeVisible();
  await page.getByRole("button", { name: "Continue" }).click();
  await expect(page.getByText("42 Checkout Street")).toBeVisible();
  await page.getByRole("button", { name: "Continue" }).click();
  await expect(page.getByText("Cash on Delivery", { exact: true })).toBeVisible();
  if (testInfo.project.name === "mobile") await page.getByLabel("Razorpay online payment").check();
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByRole("button", { name: testInfo.project.name === "mobile" ? "Pay securely" : "Place COD order" }).click();
  await expect(page.getByText("Order placed beautifully.")).toBeVisible();
  await expect(page.locator(".order-status", { hasText: "PLACED" })).toBeVisible();
  const placedOrderId = Number(new URL(page.url()).pathname.split("/").pop());
  await page.goto("/cart");
  await expect(page.getByRole("heading", { name: "Your bag is empty." })).toBeVisible();
  await page.goBack();
  if (testInfo.project.name === "desktop") {
    page.on("dialog", (dialog) => dialog.accept());
    await page.getByRole("button", { name: "Cancel order" }).click();
    await expect(page.getByRole("heading", { name: "Order cancelled." })).toBeVisible();
    await expect(page.getByText("CANCELLED", { exact: true }).first()).toBeVisible();
  }
  await page.goto("/account");
  await page.getByRole("button", { name: "Sign out" }).click();
  await page.goto("/login?next=%2Fadmin%2Fproducts");
  await page.getByLabel("Email address").fill("admin@yoranzify.local");
  await page.getByLabel("Password", { exact: true }).fill("Yoranzify123!");
  await page.getByRole("button", { name: /Sign in/ }).click();
  await expect(page).toHaveURL(/\/admin\/products$/);
  if (testInfo.project.name === "desktop") {
    await page.goto(`/admin/customers?q=${encodeURIComponent(cartEmail)}`);
    const customerRow = page.locator(".customer-table article").filter({ hasText: cartEmail });
    await customerRow.getByRole("button", { name: "Disable" }).click();
    await expect(customerRow).toContainText("Disabled");
    await customerRow.getByRole("button", { name: "Enable" }).click();
    await expect(customerRow).toContainText("Active");
  }
  if (testInfo.project.name === "mobile") {
    await page.goto(`/admin/orders/${placedOrderId}`);
    await page.getByRole("button", { name: "Mark CONFIRMED" }).click();
    await page.getByRole("button", { name: "Mark PACKED" }).click();
    await page.getByLabel("Courier").fill("Blue Dart");
    await page.getByLabel("Tracking number").fill(`AWB${placedOrderId}`);
    await page.getByLabel("Tracking URL").fill(`https://example.com/track/${placedOrderId}`);
    await page.getByLabel("Internal notes").fill("Quality check complete.");
    await page.getByRole("button", { name: "Save details" }).click();
    await expect(page.getByRole("status")).toContainText("Saved successfully");
    await page.getByRole("button", { name: "Mark SHIPPED" }).click();
    await page.getByRole("button", { name: "Mark OUT FOR DELIVERY" }).click();
    await page.getByRole("button", { name: "Mark DELIVERED" }).click();
    await expect(page.locator(".order-status", { hasText: "DELIVERED" })).toBeVisible();
  }
  const deniedJob = await page.request.post("/api/jobs/operations");
  expect(deniedJob.status()).toBe(401);
  const job = await page.request.post("/api/jobs/operations", { headers: { Authorization: "Bearer playwright-operations-secret-123456789" } });
  expect(job.ok()).toBe(true);
  await page.goto("/admin/notifications");
  await expect(page.getByRole("heading", { name: "Email outbox" })).toBeVisible();
  await expect(page.getByText(/WELCOME|ORDER_PLACED|PAYMENT_CONFIRMED|DELIVERED/).first()).toBeVisible();
  const medium = created.variants.find((variant: { sku: string }) => variant.sku === skuM);
  const adjustments = await Promise.all([1, 2].map(() => page.request.post(`/api/admin/inventory/${medium.id}`, { data: { delta: -8, reason: "CORRECTION", note: "Concurrency acceptance test" } })));
  expect(adjustments.map((response) => response.status()).sort()).toEqual([200, 409]);
  const refreshed = await (await page.request.get(`/api/admin/products/${created.id}`)).json();
  expect(refreshed.product.variants.find((variant: { sku: string }) => variant.sku === skuM).stockQuantity).toBe(testInfo.project.name === "mobile" ? 1 : 2);
  await page.goto("/admin/products");
  if (testInfo.project.name === "mobile") page.on("dialog", (dialog) => dialog.accept());
  const row = page.locator(".product-table-row").filter({ hasText: productName });
  await row.getByRole("button", { name: "Archive product" }).click();
  await expect(row).toHaveClass(/archived/);
  await page.goto(`/products/${created.slug}`);
  await expect(page.getByRole("heading", { name: "That page slipped away." })).toBeVisible();
});

test("admin publishes and controls homepage campaigns", async ({ page }, testInfo) => {
  const title = `Campaign ${testInfo.project.name}-${Date.now()}`;
  await page.goto("/login?next=%2Fadmin%2Fbanners");
  await page.getByLabel("Email address").fill("admin@yoranzify.local");
  await page.getByLabel("Password", { exact: true }).fill("Yoranzify123!");
  await page.getByRole("button", { name: /Sign in/ }).click();
  await expect(page).toHaveURL(/\/admin\/banners$/);
  const stale = await (await page.request.get("/api/admin/homepage")).json();
  for (const banner of stale.banners.filter((item: { title: string }) => item.title.startsWith(`Campaign ${testInfo.project.name}-`))) await page.request.delete(`/api/admin/homepage/banners/${banner.id}`);
  await page.reload();
  await page.getByRole("button", { name: "New banner" }).click();
  await page.getByLabel("Desktop image").setInputFiles("public/images/yoranzify-hero.png");
  await expect(page.getByText("Image ready").first()).toBeVisible();
  await page.getByLabel("Mobile image").setInputFiles("public/images/yoranzify-hero.png");
  await expect(page.getByText("Image ready")).toHaveCount(2);
  await page.getByLabel("Accessible image description").fill(`${title} editorial model`);
  await page.getByLabel("Headline").fill(title);
  await page.getByLabel("Subtitle").fill("A responsive campaign from the homepage studio.");
  await page.getByRole("button", { name: "Save banner" }).click();
  await expect(page.getByRole("heading", { name: title })).toBeVisible();

  const cms = await (await page.request.get("/api/admin/homepage")).json();
  const created = cms.banners.find((banner: { title: string }) => banner.title === title);
  expect(created).toBeTruthy();
  const secondTitle = `${title} second`;
  const second = await page.request.post("/api/admin/homepage", { data: { kind: "banner", data: { desktopMediaId: created.desktopMediaId, mobileMediaId: created.mobileMediaId, altText: `${secondTitle} editorial model`, title: secondTitle, subtitle: "Second carousel story.", buttonText: "Explore", buttonUrl: "/shop", position: created.position + 1, startsAt: null, endsAt: null, enabled: true } } });
  expect(second.ok()).toBe(true);
  const secondId = (await second.json()).banner.id;

  await page.goto("/");
  const carousel = page.getByRole("region", { name: "Featured collections" });
  const findSlide = async (heading: string) => { for (let attempt = 0; attempt < 12; attempt++) { if (await carousel.getByRole("heading", { name: heading, exact: true }).count()) return; await carousel.getByRole("button", { name: "Next banner" }).click(); } throw new Error(`Carousel did not reach ${heading}`); };
  await findSlide(title);
  await expect(carousel.getByRole("heading", { name: title, exact: true })).toBeVisible();
  await expect(carousel.locator("picture source")).toHaveAttribute("srcset", `/api/media/${created.mobileMediaId}`);
  await findSlide(secondTitle);
  await expect(carousel.getByRole("heading", { name: secondTitle, exact: true })).toBeVisible();
  await expect(carousel.getByRole("button", { name: /carousel/ })).toBeVisible();

  const disabled = await page.request.patch(`/api/admin/homepage/banners/${created.id}`, { data: { desktopMediaId: created.desktopMediaId, mobileMediaId: created.mobileMediaId, altText: created.altText, title: created.title, subtitle: created.subtitle, buttonText: created.buttonText, buttonUrl: created.buttonUrl, position: created.position, startsAt: created.startsAt, endsAt: created.endsAt, enabled: false } });
  expect(disabled.ok()).toBe(true);
  await page.goto("/");
  await expect(page.getByRole("heading", { name: title, exact: true })).toHaveCount(0);

  await page.request.delete(`/api/admin/homepage/banners/${created.id}`);
  await page.request.delete(`/api/admin/homepage/banners/${secondId}`);
  if (testInfo.project.name === "desktop") {
    await page.goto("/admin/banners");
    const testimonials = page.locator(".section-editor article").filter({ hasText: "Testimonials" });
    await testimonials.locator('input[type="checkbox"]').check();
    await page.getByRole("button", { name: "Save layout" }).click();
    await expect(page.getByRole("status")).toContainText("saved");
    await page.goto("/");
    await expect(page.getByRole("heading", { name: "Worn and loved" })).toBeVisible();
    await page.goto("/admin/banners");
    await page.locator(".section-editor article").filter({ hasText: "Testimonials" }).locator('input[type="checkbox"]').uncheck();
    await page.getByRole("button", { name: "Save layout" }).click();
  }
});
