import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Check } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { CancelOrderButton } from "@/components/order-actions";
import { CANCELLABLE_STATUSES, orderInclude } from "@/lib/orders";
const money = (value: number) => `₹${(value / 100).toLocaleString("en-IN")}`;
export default async function OrderPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ placed?: string }> }) { const user = await requireUser(); const order = await prisma.order.findFirst({ where: { id: Number((await params).id), userId: user.id }, include: orderInclude }); if (!order) notFound(); const placed = (await searchParams).placed === "1"; return <section className="container order-detail-page">{placed && <div className="order-success"><Check /><div><strong>Order placed beautifully.</strong><span>We’ll prepare your edit for delivery.</span></div></div>}<Link className="back-link" href="/account/orders"><ArrowLeft size={14} />All orders</Link><header><div><p className="eyebrow">Order {order.orderNumber}</p><h1>{order.status === "CANCELLED" ? "Order cancelled." : "Your edit is in motion."}</h1></div><div><span className={`order-status ${order.status.toLowerCase()}`}>{order.status.replaceAll("_", " ")}</span><strong>{money(order.totalPaise)}</strong></div></header><div className="order-detail-grid"><main><section className="order-items"><h2>Pieces</h2>{order.items.map((item) => <article key={item.id}><div><strong>{item.productName}</strong><small>{item.colorName} / {item.sizeName} · {item.sku} · Qty {item.quantity}</small></div><span>{money(item.lineTotalPaise)}</span></article>)}</section><section className="order-timeline"><h2>Journey</h2>{order.history.map((item) => <div key={item.id}><i><Check size={12} /></i><div><strong>{item.status.replaceAll("_", " ")}</strong><small>{new Date(item.createdAt).toLocaleString("en-IN")}{item.note ? ` · ${item.note}` : ""}</small></div></div>)}</section></main><aside><h2>Delivery</h2><p><strong>{order.addressFullName}</strong><br />{order.addressLine1}{order.addressLine2 ? `, ${order.addressLine2}` : ""}<br />{order.addressCity}, {order.addressState} {order.addressPostalCode}<br />+91 {order.addressMobile}</p><h2>Payment</h2><p>Cash on Delivery · {order.paymentStatus}</p><dl><div><dt>Subtotal</dt><dd>{money(order.merchandiseSubtotalPaise)}</dd></div><div><dt>Discounts</dt><dd>−{money(order.automaticDiscountPaise + order.couponDiscountPaise)}</dd></div><div><dt>Shipping</dt><dd>{money(order.shippingPaise)}</dd></div><div><dt>Tax included</dt><dd>{money(order.taxPaise)}</dd></div><div><dt>Total</dt><dd>{money(order.totalPaise)}</dd></div></dl>{CANCELLABLE_STATUSES.includes(order.status) && <CancelOrderButton id={order.id} />}</aside></div></section>; }
