import Image from "next/image";
import Link from "next/link";
import { Plus } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { productInclude } from "@/lib/products";
import { ProductActions } from "@/components/product-actions";

export default async function ProductsPage() { const products = await prisma.product.findMany({ include: productInclude, orderBy: { createdAt: "desc" }, take: 50 }); return <main className="admin-main settings-page"><header className="admin-top"><div><p className="eyebrow">Catalogue</p><h1>Products</h1></div><Link className="button button-dark" href="/admin/products/new"><Plus size={16} />Add product</Link></header><p className="settings-lead">Manage the pieces, prices, variant combinations, and availability your customers see.</p><section className="product-admin-table"><div className="product-table-head"><span>Product</span><span>Status</span><span>Variants</span><span>Stock</span><span>Price</span><span /></div>{products.length ? products.map((product) => { const activeVariants = product.variants.filter((variant) => variant.isActive); return <div className={`product-table-row ${product.archivedAt ? "archived" : ""}`} key={product.id}><div className="admin-product"><span>{product.images[0] ? <Image src={`/api/media/${product.images[0].media.id}`} alt="" fill unoptimized sizes="58px" /> : product.name.charAt(0)}</span><div><strong>{product.name}</strong><small>{product.skuReference} · {product.category.name}</small></div></div><span className={`visibility ${product.status === "ACTIVE" && !product.archivedAt ? "visible" : ""}`}>{product.archivedAt ? "Archived" : product.status}</span><span>{activeVariants.length}</span><span>{activeVariants.reduce((total, item) => total + item.stockQuantity, 0)}</span><span>₹{((product.salePricePaise ?? product.regularPricePaise) / 100).toLocaleString("en-IN")}</span><ProductActions id={product.id} archived={Boolean(product.archivedAt)} /></div>; }) : <div className="admin-empty"><ImagePlus /><h2>Your first collection starts here.</h2><p>Add a product with colour and size variants to begin.</p></div>}</section></main>; }

function ImagePlus() { return <span className="empty-glyph">Y</span>; }
