import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

type Page = { title: string; intro: string; sections: [string, string][] };
const pages: Record<string, Page> = {
  about: { title: "About Yoranzify", intro: "A modern Indian label built around expressive essentials and considered wardrobes.", sections: [["Our point of view", "We design versatile silhouettes with an emphasis on comfort, thoughtful detail, and repeat wear."], ["Made with intention", "Product pages describe materials and care information for each piece. We continue to improve our sourcing and production practices."]] },
  contact: { title: "Contact us", intro: "We’re here to help with products, sizing, delivery, and orders.", sections: [["Customer care", "Email the address shown in the website footer and include your order number when asking about an existing purchase."], ["Response time", "We aim to respond within two business days, Monday through Saturday, excluding public holidays."]] },
  shipping: { title: "Shipping policy", intro: "Orders are currently delivered to serviceable addresses in India.", sections: [["Processing", "Orders are normally prepared within two business days. During launches or holidays, processing can take longer."], ["Charges and estimates", "The checkout page shows the applicable shipping charge and estimated service availability before you place an order."], ["Tracking", "When your parcel ships, its courier and tracking details appear in your account and are sent by email."]] },
  returns: { title: "Returns and refunds", intro: "Contact customer care within seven days of delivery if an eligible item is unsuitable.", sections: [["Eligibility", "Items must be unused, unworn, unwashed, and returned with original tags and packaging. Hygiene-sensitive, customized, and final-sale items may be ineligible."], ["Inspection and refund", "Returned items are inspected before approval. Approved refunds are issued to the original payment method; bank processing times vary."], ["Damaged items", "Report an incorrect or damaged item promptly with clear photographs so we can resolve it."]] },
  cancellation: { title: "Cancellation policy", intro: "Orders can be cancelled from your account while their status remains eligible for online cancellation.", sections: [["Before packing", "Cancellation is generally available while an order is awaiting payment, placed, or confirmed. Stock is restored automatically."], ["After dispatch", "Once packing or shipping begins, use the return process after delivery if the item is eligible."]] },
  privacy: { title: "Privacy policy", intro: "We collect only the information needed to operate your account, orders, support, and secure payments.", sections: [["Information we use", "This includes contact details, delivery addresses, order history, session data, and operational security records."], ["Payments", "Payment credentials are handled by the payment provider. Yoranzify stores gateway references and payment status, not complete card details."], ["Sharing and retention", "Information is shared with service providers only as needed for payment, delivery, communication, security, and legal obligations. Retention follows operational and statutory requirements."], ["Your choices", "Contact customer care to request access or correction of your personal information, subject to identity verification and legal retention duties."]] },
  terms: { title: "Terms of use", intro: "By using this website, you agree to provide accurate information and use the service lawfully.", sections: [["Products and pricing", "Availability, descriptions, colors, and prices may change. We may correct genuine errors before dispatch and will contact you if an order is affected."], ["Orders", "An order confirmation records receipt of your request. We may cancel an order affected by unavailable stock, payment failure, suspected misuse, or an obvious error and will reverse collected funds where applicable."], ["Acceptable use", "Do not interfere with the service, attempt unauthorized access, automate abusive requests, or misuse content and trademarks."], ["Liability", "Nothing in these terms excludes rights or remedies that cannot legally be excluded under applicable Indian law."]] }
};
export function generateStaticParams() { return Object.keys(pages).map((legal) => ({ legal })); }
export async function generateMetadata({ params }: { params: Promise<{ legal: string }> }): Promise<Metadata> { const key = (await params).legal; const page = pages[key]; return page ? { title: page.title, description: page.intro, alternates: { canonical: `/${key}` } } : {}; }
export default async function LegalPage({ params }: { params: Promise<{ legal: string }> }) { const page = pages[(await params).legal]; if (!page) notFound(); return <article className="container legal-page"><p className="eyebrow">Yoranzify policies</p><h1>{page.title}</h1><p className="legal-intro">{page.intro}</p><p className="legal-updated">Last updated: 14 September 2026</p>{page.sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}<aside><strong>Need help?</strong><p>Contact customer care before purchasing if you need clarification.</p><Link className="text-link" href="/contact">Contact Yoranzify</Link></aside></article>; }
