"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
const next: Record<string, string | undefined> = { PLACED: "CONFIRMED", CONFIRMED: "PACKED", PACKED: "SHIPPED", SHIPPED: "OUT_FOR_DELIVERY", OUT_FOR_DELIVERY: "DELIVERED" };
type FulfillmentMethod = "THIRD_PARTY" | "SELF_DELIVERY";
type OrderDetails = { id: number; status: string; fulfillmentMethod: FulfillmentMethod; courierName: string | null; trackingNumber: string | null; trackingUrl: string | null; internalNotes: string | null };
export function AdminOrderEditor({ order }: { order: OrderDetails }) {
  const router = useRouter(); const [form, setForm] = useState({ fulfillmentMethod: order.fulfillmentMethod, courierName: order.courierName || "", trackingNumber: order.trackingNumber || "", trackingUrl: order.trackingUrl || "", internalNotes: order.internalNotes || "" }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const target = next[order.status]; const trackingReady = form.fulfillmentMethod === "SELF_DELIVERY" || Boolean(form.courierName.trim() && form.trackingNumber.trim());
  async function patch(url: string, body: unknown) { const response = await fetch(url, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || "Update failed."); }
  async function saveDetails() { setBusy(true); setMessage(""); try { await patch(`/api/admin/orders/${order.id}`, form); setMessage("Fulfilment details saved."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Update failed."); } finally { setBusy(false); } }
  async function advance() { if (!target) return; setBusy(true); setMessage(""); try { if (target === "SHIPPED") await patch(`/api/admin/orders/${order.id}`, form); await patch(`/api/admin/orders/${order.id}/status`, { status: target }); setMessage(`Order marked ${target.replaceAll("_", " ").toLowerCase()}.`); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Update failed."); } finally { setBusy(false); } }
  return <div className="admin-order-editor"><h2>Fulfilment controls</h2><fieldset className="fulfilment-method"><legend>Shipping method</legend><label className={form.fulfillmentMethod === "SELF_DELIVERY" ? "selected" : ""}><input type="radio" name="fulfillmentMethod" checked={form.fulfillmentMethod === "SELF_DELIVERY"} onChange={() => setForm({ ...form, fulfillmentMethod: "SELF_DELIVERY" })} /><span><strong>Self delivery</strong><small>Manage delivery status without a tracking ID.</small></span></label><label className={form.fulfillmentMethod === "THIRD_PARTY" ? "selected" : ""}><input type="radio" name="fulfillmentMethod" checked={form.fulfillmentMethod === "THIRD_PARTY"} onChange={() => setForm({ ...form, fulfillmentMethod: "THIRD_PARTY" })} /><span><strong>Third-party courier</strong><small>Courier and tracking ID are required before shipping.</small></span></label></fieldset><div className="tracking-fields">{form.fulfillmentMethod === "THIRD_PARTY" && <><label><span>Courier</span><input aria-label="Courier" value={form.courierName} onChange={(event) => setForm({ ...form, courierName: event.target.value })} /></label><label><span>Tracking ID</span><input aria-label="Tracking ID" value={form.trackingNumber} onChange={(event) => setForm({ ...form, trackingNumber: event.target.value })} /></label><label className="wide"><span>Tracking URL (optional)</span><input aria-label="Tracking URL" value={form.trackingUrl} onChange={(event) => setForm({ ...form, trackingUrl: event.target.value })} /></label></>}<label className="wide"><span>Internal notes</span><textarea aria-label="Internal notes" rows={4} value={form.internalNotes} onChange={(event) => setForm({ ...form, internalNotes: event.target.value })} /></label></div>{target === "SHIPPED" && form.fulfillmentMethod === "THIRD_PARTY" && !trackingReady && <p className="tracking-hint">Enter the courier and tracking ID to enable Mark shipped.</p>}{message && <p className={message.includes("failed") || message.includes("required") ? "form-error" : "form-success"} role="status">{message}</p>}<div className="admin-order-buttons"><button className="button" disabled={busy} onClick={saveDetails}>Save fulfilment</button>{target && <button className="button button-dark" disabled={busy || (target === "SHIPPED" && !trackingReady)} onClick={advance}>Mark {target.replaceAll("_", " ")}</button>}</div></div>;
}
