"use client";
import Image from "next/image";
import Link from "next/link";
import { createContext, useCallback, useContext, useEffect, useState } from "react";
import { Minus, Plus, ShoppingBag, Trash2, X } from "lucide-react";

export type CartView = { id: number | null; items: { id: number; variantId: number; quantity: number; allowedQuantity: number; available: boolean; stockChanged: boolean; priceChanged: boolean; previousUnitPricePaise: number; unitPricePaise: number; automaticDiscountPaise: number; promotionName: string | null; lineTotalPaise: number; sku: string; color: string; size: string; product: { name: string; slug: string; imageUrl: string | null } }[]; itemCount: number; subtotalPaise: number; automaticDiscountPaise: number; coupon: { code: string; description: string | null } | null; couponDiscountPaise: number; discountedSubtotalPaise: number; shippingPaise: number; platformFeePaise: number; freeShippingAbovePaise: number; freeShippingRemainingPaise: number; totalPaise: number };
const empty: CartView = { id: null, items: [], itemCount: 0, subtotalPaise: 0, automaticDiscountPaise: 0, coupon: null, couponDiscountPaise: 0, discountedSubtotalPaise: 0, shippingPaise: 0, platformFeePaise: 0, freeShippingAbovePaise: 199900, freeShippingRemainingPaise: 199900, totalPaise: 0 };
const CartContext = createContext<{ cart: CartView; open: boolean; busy: boolean; message: string; setOpen: (open: boolean) => void; add: (variantId: number, quantity: number) => Promise<boolean>; update: (id: number, quantity: number) => Promise<void>; remove: (id: number) => Promise<void>; clear: () => Promise<void>; applyCoupon: (code: string) => Promise<boolean>; removeCoupon: () => Promise<void> } | null>(null);

async function requestCart(url: string, init?: RequestInit) { const response = await fetch(url, init); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to update your bag."); return body as CartView; }
export function CartProvider({ children }: { children: React.ReactNode }) { const [cart, setCart] = useState(empty); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); useEffect(() => { requestCart("/api/cart").then(setCart).catch(() => undefined); }, []); const mutate = useCallback(async (url: string, init: RequestInit) => { setBusy(true); setMessage(""); try { setCart(await requestCart(url, { ...init, headers: { "Content-Type": "application/json", ...init.headers } })); return true; } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update your bag."); return false; } finally { setBusy(false); } }, []); const add = async (variantId: number, quantity: number) => { const ok = await mutate("/api/cart", { method: "POST", body: JSON.stringify({ variantId, quantity }) }); if (ok) setOpen(true); return ok; }; const update = async (id: number, quantity: number) => { await mutate(`/api/cart/items/${id}`, { method: "PATCH", body: JSON.stringify({ quantity }) }); }; const remove = async (id: number) => { await mutate(`/api/cart/items/${id}`, { method: "DELETE" }); }; const clear = async () => { await mutate("/api/cart", { method: "DELETE" }); }; const applyCoupon = (code: string) => mutate("/api/cart/coupon", { method: "POST", body: JSON.stringify({ code }) }); const removeCoupon = async () => { await mutate("/api/cart/coupon", { method: "DELETE" }); }; return <CartContext.Provider value={{ cart, open, busy, message, setOpen, add, update, remove, clear, applyCoupon, removeCoupon }}>{children}<CartDrawer /></CartContext.Provider>; }
export function useCart() { const value = useContext(CartContext); if (!value) throw new Error("useCart must be inside CartProvider"); return value; }
const money = (paise: number) => `₹${(paise / 100).toLocaleString("en-IN")}`;

function CartItems({ compact = false }: { compact?: boolean }) { const { cart, busy, update, remove } = useCart(); return <div className={`cart-items ${compact ? "compact" : ""}`}>{cart.items.map((item) => <article className="cart-item" key={item.id}>{item.product.imageUrl ? <Image src={item.product.imageUrl} alt="" width={compact ? 82 : 120} height={compact ? 105 : 155} unoptimized /> : <span className="cart-art">{item.product.name.charAt(0)}</span>}<div className="cart-item-copy"><Link href={`/products/${item.product.slug}`}>{item.product.name}</Link><small>{item.color} / {item.size} · {item.sku}</small>{item.promotionName && <p className="cart-promotion">{item.promotionName} · −{money(item.automaticDiscountPaise)}</p>}{item.priceChanged && <p className="cart-notice">Price updated from {money(item.previousUnitPricePaise)}</p>}{(!item.available || item.stockChanged) && <p className="cart-notice error">{!item.available ? "This piece is unavailable." : `Only ${item.allowedQuantity} now available.`}</p>}<div className="cart-item-bottom"><div className="quantity"><button disabled={busy || item.quantity <= 1} aria-label={`Decrease ${item.product.name}`} onClick={() => update(item.id, item.quantity - 1)}><Minus size={13} /></button><span>{item.quantity}</span><button disabled={busy || item.quantity >= item.allowedQuantity} aria-label={`Increase ${item.product.name}`} onClick={() => update(item.id, item.quantity + 1)}><Plus size={13} /></button></div><strong>{money(item.lineTotalPaise)}</strong><button disabled={busy} className="cart-remove" aria-label={`Remove ${item.product.name}`} onClick={() => remove(item.id)}><Trash2 size={15} /></button></div></div></article>)}</div>; }
function CartSummary({ coupons = false }: { coupons?: boolean }) { const { cart, applyCoupon, removeCoupon, busy } = useCart(); const [code, setCode] = useState(""); const progress = Math.min(100, cart.discountedSubtotalPaise / cart.freeShippingAbovePaise * 100); return <div className="cart-summary">{cart.freeShippingRemainingPaise > 0 ? <p>Add {money(cart.freeShippingRemainingPaise)} more for complimentary shipping.</p> : <p>You’ve unlocked complimentary shipping.</p>}<div className="shipping-progress"><i style={{ width: `${progress}%` }} /></div>{coupons && (cart.coupon ? <div className="coupon-applied"><div><strong>{cart.coupon.code}</strong><small>{cart.coupon.description || "Coupon applied"}</small></div><button disabled={busy} onClick={removeCoupon}>Remove</button></div> : <form className="coupon-form" onSubmit={async (event) => { event.preventDefault(); if (await applyCoupon(code)) setCode(""); }}><label htmlFor="coupon-code">Coupon code</label><div><input id="coupon-code" value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} placeholder="ENTER CODE" /><button disabled={busy || code.length < 3}>Apply</button></div></form>)}<dl><div><dt>Subtotal</dt><dd>{money(cart.subtotalPaise)}</dd></div>{cart.automaticDiscountPaise > 0 && <div className="discount-row"><dt>Promotions</dt><dd>−{money(cart.automaticDiscountPaise)}</dd></div>}{cart.couponDiscountPaise > 0 && <div className="discount-row"><dt>Coupon {cart.coupon?.code}</dt><dd>−{money(cart.couponDiscountPaise)}</dd></div>}<div><dt>Shipping</dt><dd>{cart.shippingPaise ? money(cart.shippingPaise) : "Complimentary"}</dd></div><div className="cart-total"><dt>Total</dt><dd>{money(cart.totalPaise)}</dd></div></dl></div>; }
function CartDrawer() { const { cart, open, setOpen, message } = useCart(); if (!open) return null; return <><aside className="cart-drawer open" aria-label="Shopping bag"><header><div><p className="eyebrow">Your selection</p><h2>Shopping bag <span>{cart.itemCount}</span></h2></div><button className="icon-button" aria-label="Close shopping bag" onClick={() => setOpen(false)}><X /></button></header>{message && <p className="cart-api-error" role="status">{message}</p>}{cart.items.length ? <><CartItems compact /><CartSummary /><Link className="button button-dark cart-view-link" href="/cart" onClick={() => setOpen(false)}>View bag</Link></> : <div className="cart-empty"><ShoppingBag /><h3>Your bag is waiting.</h3><p>Choose a colour and size to begin your edit.</p><Link href="/shop" className="button button-dark" onClick={() => setOpen(false)}>Explore pieces</Link></div>}</aside><button className="cart-backdrop" aria-label="Close shopping bag" onClick={() => setOpen(false)} /></>; }
export function CartPageContent() { const { cart, clear, busy, message } = useCart(); if (!cart.items.length) return <div className="cart-page-empty"><ShoppingBag /><h1>Your bag is empty.</h1><p>Discover considered pieces made for everyday expression.</p><Link href="/shop" className="button button-dark">Shop the collection</Link></div>; return <><header className="cart-page-head"><div><p className="eyebrow">Your selection</p><h1>Shopping bag</h1></div><button disabled={busy} onClick={clear}>Clear bag</button></header>{message && <p className="cart-api-error" role="status">{message}</p>}<div className="cart-page-grid"><CartItems /><div><CartSummary coupons /><Link className={`button button-dark checkout-placeholder ${cart.items.some((item) => !item.available || item.stockChanged) ? "disabled" : ""}`} href="/checkout">Secure checkout</Link></div></div></>; }
