"use client";
import { useState } from "react";
import type { CategoryView } from "@/lib/categories";
function flatten(items: CategoryView[]): CategoryView[] { return items.flatMap((item) => [item, ...flatten(item.children)]); }
export function CategoryShippingRules({ categories }: { categories: CategoryView[] }) {
  const [rows, setRows] = useState(flatten(categories)); const [message, setMessage] = useState("");
  async function save(category: CategoryView) { setMessage(""); const response = await fetch(`/api/admin/categories/${category.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: category.name, slug: category.slug, description: category.description ?? "", parentId: category.parentId, imageMediaId: category.imageMediaId, displayOrder: category.displayOrder, isVisible: category.isVisible, shippingChargeRupees: category.shippingChargeRupees, freeShippingAboveRupees: category.freeShippingAboveRupees }) }); const result = await response.json(); setMessage(response.ok ? `${category.name} shipping saved.` : result.error?.message || "Could not save shipping rule."); }
  return <section className="settings-section"><div className="settings-section-head"><div><p className="eyebrow">Delivery pricing</p><h2>Category shipping rules</h2></div><p>Blank values use the store defaults. Mixed carts charge the highest applicable category fee once.</p></div><div className="shipping-rule-list">{rows.filter((row) => !row.archivedAt).map((category) => <article key={category.id}><strong>{category.name}</strong><label><span>Shipping charge (₹)</span><input type="number" min="0" value={category.shippingChargeRupees ?? ""} onChange={(e) => setRows(rows.map((row) => row.id === category.id ? { ...row, shippingChargeRupees: e.target.value === "" ? null : Number(e.target.value) } : row))} /></label><label><span>Free above (₹)</span><input type="number" min="0" value={category.freeShippingAboveRupees ?? ""} onChange={(e) => setRows(rows.map((row) => row.id === category.id ? { ...row, freeShippingAboveRupees: e.target.value === "" ? null : Number(e.target.value) } : row))} /></label><button className="button" onClick={() => save(category)}>Save</button></article>)}</div>{message && <p className="form-success" role="status">{message}</p>}</section>;
}
