"use client";

import Image from "next/image";
import { Archive, ArrowDown, ArrowUp, ChevronRight, Eye, EyeOff, ImagePlus, LoaderCircle, Pencil, Plus, Upload, X } from "lucide-react";
import { FormEvent, useRef, useState } from "react";
import type { CategoryView } from "@/lib/categories";

type Editing = { id?: number; name: string; slug: string; description: string; parentId: number | null; imageMediaId: number | null; imageUrl: string | null; displayOrder: number; isVisible: boolean };
const empty = (parentId: number | null = null): Editing => ({ name: "", slug: "", description: "", parentId, imageMediaId: null, imageUrl: null, displayOrder: 0, isVisible: true });

function flatten(items: CategoryView[], depth = 0): { category: CategoryView; depth: number }[] { return items.flatMap((category) => [{ category, depth }, ...flatten(category.children, depth + 1)]); }

export function CategoryManager({ initial }: { initial: CategoryView[] }) {
  const [tree, setTree] = useState(initial); const [editing, setEditing] = useState<Editing | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function refresh() { const response = await fetch("/api/admin/categories"); const result = await response.json(); if (response.ok) setTree(result.categories); }
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editing) return; setBusy(true); setMessage(""); const form = new FormData(event.currentTarget);
    const payload = { name: form.get("name"), slug: form.get("slug"), description: form.get("description"), parentId: form.get("parentId") ? Number(form.get("parentId")) : null, imageMediaId: editing.imageMediaId, displayOrder: Number(form.get("displayOrder")), isVisible: form.has("isVisible") };
    const response = await fetch(editing.id ? `/api/admin/categories/${editing.id}` : "/api/admin/categories", { method: editing.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); setBusy(false);
    if (!response.ok) return setMessage(result.error?.message ?? "Category could not be saved."); setEditing(null); await refresh();
  }
  async function patch(category: CategoryView, changes: Partial<Editing>) { setBusy(true); const response = await fetch(`/api/admin/categories/${category.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: category.name, slug: category.slug, description: category.description ?? "", parentId: category.parentId, imageMediaId: category.imageMediaId, displayOrder: category.displayOrder, isVisible: category.isVisible, ...changes }) }); const result = await response.json(); setBusy(false); if (!response.ok) setMessage(result.error?.message ?? "Update failed."); else await refresh(); }
  async function archive(category: CategoryView) { if (!confirm(`Archive “${category.name}”? It will disappear from the store.`)) return; setBusy(true); const response = await fetch(`/api/admin/categories/${category.id}`, { method: "DELETE" }); const result = await response.json(); setBusy(false); if (!response.ok) setMessage(result.error?.message ?? "Archive failed."); else await refresh(); }
  async function move(category: CategoryView, direction: -1 | 1) { const siblings = (category.parentId ? flatten(tree).find(({ category: item }) => item.id === category.parentId)?.category.children : tree) ?? []; const index = siblings.findIndex((item) => item.id === category.id); const target = index + direction; if (target < 0 || target >= siblings.length) return; const ids = siblings.map((item) => item.id); [ids[index], ids[target]] = [ids[target], ids[index]]; await fetch("/api/admin/categories/reorder", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ parentId: category.parentId, orderedIds: ids }) }); await refresh(); }

  function Row({ category, depth }: { category: CategoryView; depth: number }) { return <div className={`category-admin-row ${category.archivedAt ? "archived" : ""}`} style={{ paddingLeft: `${18 + depth * 34}px` }}><span className="category-thumb">{category.imageUrl ? <Image src={category.imageUrl} alt="" fill unoptimized sizes="52px" /> : <ImagePlus size={18} />}</span><div className="category-row-main"><strong>{category.name}</strong><small>/{category.slug} · {category.children.length} subcategories</small></div><span className={`visibility ${category.isVisible && !category.archivedAt ? "visible" : ""}`}>{category.isVisible && !category.archivedAt ? "Visible" : "Hidden"}</span>{!category.archivedAt && <div className="category-actions"><button aria-label={`Move ${category.name} up`} onClick={() => move(category, -1)}><ArrowUp size={15} /></button><button aria-label={`Move ${category.name} down`} onClick={() => move(category, 1)}><ArrowDown size={15} /></button><button aria-label={`${category.isVisible ? "Hide" : "Show"} ${category.name}`} onClick={() => patch(category, { isVisible: !category.isVisible })}>{category.isVisible ? <EyeOff size={15} /> : <Eye size={15} />}</button><button aria-label={`Add child to ${category.name}`} onClick={() => setEditing(empty(category.id))}><Plus size={15} /></button><button aria-label={`Edit ${category.name}`} onClick={() => setEditing({ ...category, description: category.description ?? "" })}><Pencil size={15} /></button><button aria-label={`Archive ${category.name}`} onClick={() => archive(category)}><Archive size={15} /></button></div>}</div>; }
  const rows = flatten(tree);
  return <><div className="category-toolbar"><div><strong>{rows.filter(({ category }) => !category.archivedAt).length} active categories</strong><span>Drag-free accessible ordering controls included</span></div><button className="button button-dark" onClick={() => setEditing(empty())}><Plus size={16} />Add category</button></div>{message && <p className="category-message" role="status">{message}</p>}<section className="category-admin-list"><div className="category-list-head"><span>Category</span><span>Status</span><span>Actions</span></div>{rows.map(({ category, depth }) => <Row category={category} depth={depth} key={category.id} />)}</section>{editing && <CategoryDialog value={editing} categories={rows} busy={busy} message={message} onChange={setEditing} onClose={() => { setEditing(null); setMessage(""); }} onSubmit={save} />}</>;
}

function CategoryDialog({ value, categories, busy, message, onChange, onClose, onSubmit }: { value: Editing; categories: { category: CategoryView; depth: number }[]; busy: boolean; message: string; onChange: (value: Editing) => void; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const fileRef = useRef<HTMLInputElement>(null); const [uploading, setUploading] = useState(false);
  async function upload(file?: File) { if (!file) return; setUploading(true); const data = new FormData(); data.set("file", file); data.set("kind", "CATEGORY"); const response = await fetch("/api/admin/media", { method: "POST", body: data }); const result = await response.json(); setUploading(false); if (response.ok) onChange({ ...value, imageMediaId: result.media.id, imageUrl: result.media.url }); }
  return <div className="dialog-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="category-dialog" role="dialog" aria-modal="true" aria-labelledby="category-dialog-title"><header><div><p className="eyebrow">Catalogue structure</p><h2 id="category-dialog-title">{value.id ? "Edit category" : "New category"}</h2></div><button className="icon-button" aria-label="Close category form" onClick={onClose}><X /></button></header><form onSubmit={onSubmit}><div className="category-image-field"><div>{value.imageUrl ? <Image src={value.imageUrl} alt="Category preview" fill unoptimized sizes="150px" /> : <ImagePlus size={30} />}</div><input hidden ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => upload(event.target.files?.[0])} /><button type="button" className="admin-secondary" onClick={() => fileRef.current?.click()} disabled={uploading}>{uploading ? <LoaderCircle className="spin" size={15} /> : <Upload size={15} />}{uploading ? "Optimizing…" : "Upload cover"}</button></div><label className="settings-field"><span>Name</span><input name="name" defaultValue={value.name} required /></label><label className="settings-field"><span>URL slug</span><input name="slug" defaultValue={value.slug} placeholder="Created from name if empty" /></label><label className="settings-field"><span>Parent category</span><select name="parentId" defaultValue={value.parentId ?? ""}><option value="">Top level</option>{categories.filter(({ category }) => category.id !== value.id && !category.archivedAt).map(({ category, depth }) => <option value={category.id} key={category.id}>{"— ".repeat(depth)}{category.name}</option>)}</select></label><label className="settings-field"><span>Description</span><textarea name="description" defaultValue={value.description} rows={4} /></label><label className="settings-field"><span>Display order</span><input name="displayOrder" type="number" min="0" defaultValue={value.displayOrder} /></label><label className="dialog-check"><input name="isVisible" type="checkbox" defaultChecked={value.isVisible} />Visible on storefront</label>{message && <p className="form-error" role="status">{message}</p>}<button className="button button-dark" disabled={busy}>{busy ? <LoaderCircle className="spin" size={16} /> : <ChevronRight size={16} />}{busy ? "Saving…" : "Save category"}</button></form></section></div>;
}
