"use client";
import { useMemo, useState } from "react";
import { Check, ChevronLeft, ChevronRight, CreditCard, MapPin, PackageCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import type { AddressView } from "./address-manager";
import type { CartView } from "./cart";
type Method = "COD" | "RAZORPAY";
type RazorpayResult = { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string };
type RazorpayOptions = { key: string; amount: number; currency: string; order_id: string; name: string; description: string; handler: (result: RazorpayResult) => void; modal: { ondismiss: () => void }; theme: { color: string } };
declare global { interface Window { Razorpay?: new (options: RazorpayOptions) => { open: () => void; on: (event: string, callback: (error: { error?: { description?: string } }) => void) => void } } }
const money = (value: number) => `₹${(value / 100).toLocaleString("en-IN")}`;
async function loadCheckout() { if (window.Razorpay) return true; return new Promise<boolean>((resolve) => { const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; script.onload = () => resolve(true); script.onerror = () => resolve(false); document.body.appendChild(script); }); }
export function CheckoutFlow({ addresses, cart, codEnabled }: { addresses: AddressView[]; cart: CartView; codEnabled: boolean }) {
  const router = useRouter(); const [step, setStep] = useState(0); const [method, setMethod] = useState<Method>(codEnabled ? "COD" : "RAZORPAY"); const [addressId, setAddressId] = useState(addresses.find((item) => item.isDefaultShipping)?.id ?? addresses[0]?.id); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const key = useMemo(() => crypto.randomUUID(), []); const selected = addresses.find((item) => item.id === addressId);
  const fail = (message: string) => { setError(message); setBusy(false); };
  const verify = async (result: RazorpayResult) => { const response = await fetch("/api/payments/razorpay/verify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(result) }); const body = await response.json(); if (response.ok) router.replace(`/account/orders/${body.order.id}?placed=1`); else fail(body.error?.message || "Payment verification failed."); };
  const payOnline = async () => { const response = await fetch("/api/payments/razorpay", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ addressId, paymentMethod: "RAZORPAY", idempotencyKey: key }) }); const body = await response.json(); if (!response.ok) return fail(body.error?.message || "Unable to prepare payment."); const payment = body.payment; if (payment.mock) { const simulated = await fetch("/api/payments/razorpay/mock-complete", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ gatewayOrderId: payment.gatewayOrderId }) }); const result = await simulated.json(); if (simulated.ok) router.replace(`/account/orders/${result.order.id}?placed=1`); else fail(result.error?.message || "Test payment failed."); return; } if (!(await loadCheckout()) || !window.Razorpay) return fail("Razorpay Checkout could not load. Your reservation is safe to retry."); const checkout = new window.Razorpay({ key: payment.keyId, amount: payment.amountPaise, currency: payment.currency, order_id: payment.gatewayOrderId, name: "Yoranzify", description: payment.orderNumber, handler: verify, modal: { ondismiss: () => fail("Payment window closed. You can safely retry before the reservation expires.") }, theme: { color: "#59624A" } }); checkout.on("payment.failed", (event) => fail(event.error?.description || "Payment failed. Please try again.")); checkout.open(); };
  const place = async () => { if (!addressId) return; setBusy(true); setError(""); if (method === "RAZORPAY") return payOnline(); const response = await fetch("/api/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ addressId, paymentMethod: "COD", idempotencyKey: key }) }); const body = await response.json(); if (response.ok) router.replace(`/account/orders/${body.order.id}?placed=1`); else fail(body.error?.message || "Unable to place your order."); };
  return <div className="checkout-shell"><nav className="checkout-steps">{["Bag review", "Delivery", "Payment", "Confirm"].map((label, index) => <span className={index <= step ? "active" : ""} key={label}><i>{index < step ? <Check size={12} /> : index + 1}</i>{label}</span>)}</nav>
    {step === 0 && <section className="checkout-panel"><p className="eyebrow">Your edit</p><h2>Review your bag</h2>{cart.items.map((item) => <div className="checkout-line" key={item.id}><div><strong>{item.product.name}</strong><small>{item.color} / {item.size} · Qty {item.quantity}</small></div><span>{money(item.lineTotalPaise)}</span></div>)}</section>}
    {step === 1 && <section className="checkout-panel"><p className="eyebrow">Destination</p><h2>Choose delivery address</h2>{addresses.length ? <div className="checkout-addresses">{addresses.map((address) => <label className={address.id === addressId ? "selected" : ""} key={address.id}><input type="radio" name="address" checked={address.id === addressId} onChange={() => setAddressId(address.id)} /><MapPin /><span><strong>{address.fullName}</strong><small>{address.line1}, {address.city}, {address.state} {address.postalCode}</small></span></label>)}</div> : <div className="checkout-warning">Add a delivery address from your account before continuing.</div>}</section>}
    {step === 2 && <section className="checkout-panel"><p className="eyebrow">Payment</p><h2>How would you like to pay?</h2><label className={`payment-option ${method === "RAZORPAY" ? "selected" : ""}`}><input aria-label="Razorpay online payment" type="radio" name="payment" checked={method === "RAZORPAY"} onChange={() => setMethod("RAZORPAY")} /><CreditCard /><span><strong>Razorpay secure payment</strong><small>UPI, cards, netbanking and supported wallets.</small></span></label>{codEnabled && <label className={`payment-option ${method === "COD" ? "selected" : ""}`}><input aria-label="Cash on Delivery" type="radio" name="payment" checked={method === "COD"} onChange={() => setMethod("COD")} /><PackageCheck /><span><strong>Cash on Delivery</strong><small>Pay when your order arrives.</small></span></label>}</section>}
    {step === 3 && <section className="checkout-panel"><p className="eyebrow">Final review</p><h2>Ready to place your order</h2>{selected && <div className="checkout-destination"><strong>Deliver to {selected.fullName}</strong><p>{selected.line1}, {selected.city}, {selected.state} {selected.postalCode}</p></div>}<p className="checkout-method">Payment: <strong>{method === "COD" ? "Cash on Delivery" : "Razorpay secure payment"}</strong></p><OrderTotals cart={cart} />{error && <p className="form-error" role="status">{error}</p>}</section>}
    <footer className="checkout-actions">{step > 0 && <button className="button" disabled={busy} onClick={() => setStep(step - 1)}><ChevronLeft size={15} />Back</button>}<button className="button button-dark" disabled={busy || (step === 1 && !addressId)} onClick={() => step === 3 ? place() : setStep(step + 1)}>{busy ? (method === "RAZORPAY" ? "Opening payment…" : "Placing order…") : step === 3 ? (method === "RAZORPAY" ? "Pay securely" : "Place COD order") : "Continue"}{!busy && step < 3 && <ChevronRight size={15} />}</button></footer>
  </div>;
}
function OrderTotals({ cart }: { cart: CartView }) { return <dl className="checkout-totals"><div><dt>Subtotal</dt><dd>{money(cart.subtotalPaise)}</dd></div>{cart.automaticDiscountPaise > 0 && <div><dt>Promotions</dt><dd>−{money(cart.automaticDiscountPaise)}</dd></div>}{cart.couponDiscountPaise > 0 && <div><dt>Coupon</dt><dd>−{money(cart.couponDiscountPaise)}</dd></div>}<div><dt>Shipping</dt><dd>{cart.shippingPaise ? money(cart.shippingPaise) : "Complimentary"}</dd></div><div><dt>Total</dt><dd>{money(cart.totalPaise)}</dd></div></dl>; }
