"use client";
import Image from "next/image";
import { useState } from "react";
import { ArrowDown, ArrowUp, ImagePlus, Pencil, Plus, Trash2, X } from "lucide-react";

type Media = { id: number; width: number; height: number };
type Banner = { id: number; desktopMediaId: number; mobileMediaId: number | null; desktopMedia: Media; mobileMedia: Media | null; altText: string; title: string; subtitle: string | null; buttonText: string | null; buttonUrl: string | null; position: number; startsAt: string | Date | null; endsAt: string | Date | null; enabled: boolean };
type Section = { id: number; type: string; title: string | null; subtitle: string | null; linkUrl: string | null; enabled: boolean; position: number };
type Form = { id?: number; desktopMediaId: number | null; mobileMediaId: number | null; altText: string; title: string; subtitle: string; buttonText: string; buttonUrl: string; position: number; startsAt: string; endsAt: string; enabled: boolean };
const blank = (position: number): Form => ({ desktopMediaId: null, mobileMediaId: null, altText: "", title: "", subtitle: "", buttonText: "Shop now", buttonUrl: "/shop", position, startsAt: "", endsAt: "", enabled: true });
const localDate = (value: string | Date | null) => value ? new Date(value).toISOString().slice(0, 16) : "";
const status = (item: Banner) => { const now = Date.now(); if (!item.enabled) return "Disabled"; if (item.startsAt && +new Date(item.startsAt) > now) return "Scheduled"; if (item.endsAt && +new Date(item.endsAt) <= now) return "Expired"; return "Live"; };
const label = (type: string) => type.toLowerCase().replaceAll("_", " ").replace(/^./, (letter) => letter.toUpperCase());

export function HomepageManager({ initialBanners, initialSections }: { initialBanners: Banner[]; initialSections: Section[] }) {
  const [banners, setBanners] = useState(initialBanners); const [sections, setSections] = useState(initialSections); const [form, setForm] = useState<Form | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const refresh = async () => { const body = await (await fetch("/api/admin/homepage")).json(); setBanners(body.banners); setSections(body.sections); };
  const upload = async (file: File, mobile: boolean) => { setBusy(true); const data = new FormData(); data.append("file", file); data.append("kind", "BANNER"); const response = await fetch("/api/admin/media", { method: "POST", body: data }); const body = await response.json(); setBusy(false); if (!response.ok) return setMessage(body.error?.message || "Image upload failed."); setForm((current) => current ? { ...current, [mobile ? "mobileMediaId" : "desktopMediaId"]: body.media.id } : current); };
  const edit = (item: Banner) => setForm({ id: item.id, desktopMediaId: item.desktopMediaId, mobileMediaId: item.mobileMediaId, altText: item.altText, title: item.title, subtitle: item.subtitle || "", buttonText: item.buttonText || "", buttonUrl: item.buttonUrl || "", position: item.position, startsAt: localDate(item.startsAt), endsAt: localDate(item.endsAt), enabled: item.enabled });
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!form?.desktopMediaId) return setMessage("Upload a desktop image."); setBusy(true); setMessage(""); const data = { ...form, startsAt: form.startsAt ? new Date(form.startsAt).toISOString() : null, endsAt: form.endsAt ? new Date(form.endsAt).toISOString() : null }; const response = await fetch(form.id ? `/api/admin/homepage/banners/${form.id}` : "/api/admin/homepage", { method: form.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form.id ? data : { kind: "banner", data }) }); const body = await response.json(); setBusy(false); if (!response.ok) return setMessage(body.error?.message || "Could not save banner."); await refresh(); setForm(null); };
  const remove = async (id: number) => { if (!confirm("Delete this banner?")) return; await fetch(`/api/admin/homepage/banners/${id}`, { method: "DELETE" }); await refresh(); };
  const move = (index: number, direction: -1 | 1) => { const next = [...sections]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setSections(next.map((item, position) => ({ ...item, position }))); };
  const saveSections = async () => { setBusy(true); setMessage(""); const response = await fetch("/api/admin/homepage", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "sections", data: { sections } }) }); const body = await response.json(); setBusy(false); if (!response.ok) return setMessage(body.error?.message || "Could not save sections."); setSections(body.sections); setMessage("Homepage sections saved."); };
  return <><header className="cms-head"><div><p className="eyebrow">Visual merchandising</p><h1>Homepage studio</h1><p>Shape the storefront, schedule campaigns, and preview every story.</p></div><button className="button button-dark" onClick={() => { setMessage(""); setForm(blank(banners.length)); }}><Plus size={16} />New banner</button></header>
    <section className="cms-panel"><div className="cms-section-head"><div><p className="eyebrow">Campaign carousel</p><h2>Banners</h2></div><span>{banners.length} stories</span></div><div className="banner-admin-grid">{banners.map((item) => <article key={item.id}><div className="banner-admin-image"><Image src={`/api/media/${item.desktopMediaId}`} alt={item.altText} fill sizes="(max-width: 700px) 100vw, 33vw" /></div><div className="banner-admin-copy"><span className={`offer-state ${status(item).toLowerCase()}`}>{status(item)}</span><h3>{item.title}</h3><p>{item.subtitle || "No supporting copy"}</p><small>Position {item.position + 1}{item.startsAt ? ` · ${new Date(item.startsAt).toLocaleString("en-IN")}` : " · Always on"}</small><footer><button onClick={() => edit(item)}><Pencil size={14} />Edit</button><button aria-label={`Delete ${item.title}`} onClick={() => remove(item.id)}><Trash2 size={14} /></button></footer></div></article>)}{!banners.length && <div className="cms-empty"><ImagePlus /><h3>No campaign banners yet</h3><p>Add the first responsive fashion story.</p></div>}</div></section>
    <section className="cms-panel"><div className="cms-section-head"><div><p className="eyebrow">Page composition</p><h2>Sections</h2></div><button className="button button-dark" disabled={busy} onClick={saveSections}>Save layout</button></div><div className="section-editor">{sections.map((item, index) => <article key={item.id}><div className="section-order"><button aria-label={`Move ${label(item.type)} up`} disabled={!index} onClick={() => move(index, -1)}><ArrowUp /></button><button aria-label={`Move ${label(item.type)} down`} disabled={index === sections.length - 1} onClick={() => move(index, 1)}><ArrowDown /></button></div><div><strong>{label(item.type)}</strong><small>{item.enabled ? "Visible on storefront" : "Hidden from storefront"}</small></div><label className="switch"><input type="checkbox" checked={item.enabled} onChange={(event) => setSections(sections.map((section) => section.id === item.id ? { ...section, enabled: event.target.checked } : section))} /><span /></label></article>)}</div>{message && <p className={message.includes("saved") ? "form-success" : "form-error"} role="status">{message}</p>}</section>
    {form && <div className="offer-dialog-backdrop"><section className="offer-dialog cms-dialog" role="dialog" aria-modal="true" aria-labelledby="banner-form-title"><header><div><p className="eyebrow">Campaign story</p><h2 id="banner-form-title">{form.id ? "Edit banner" : "New banner"}</h2></div><button aria-label="Close banner form" onClick={() => setForm(null)}><X /></button></header><form onSubmit={save}><div className="banner-upload-grid"><label><span>Desktop image</span><input aria-label="Desktop image" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => event.target.files?.[0] && upload(event.target.files[0], false)} /><small>{form.desktopMediaId ? "Image ready" : "Recommended 2000 × 1000"}</small></label><label><span>Mobile image (optional)</span><input aria-label="Mobile image" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => event.target.files?.[0] && upload(event.target.files[0], true)} /><small>{form.mobileMediaId ? "Image ready" : "Recommended 900 × 1200"}</small></label></div><div className="offer-fields"><label className="wide"><span>Accessible image description</span><input required aria-label="Accessible image description" value={form.altText} onChange={(e) => setForm({ ...form, altText: e.target.value })} /></label><label className="wide"><span>Internal campaign name</span><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label className="wide"><span>Internal campaign notes</span><input value={form.subtitle} onChange={(e) => setForm({ ...form, subtitle: e.target.value })} /></label><label><span>Storefront button text</span><input placeholder="Buy now" value={form.buttonText} onChange={(e) => setForm({ ...form, buttonText: e.target.value })} /></label><label><span>Button destination</span><input placeholder="/shop" value={form.buttonUrl} onChange={(e) => setForm({ ...form, buttonUrl: e.target.value })} /></label><label><span>Position</span><input type="number" min="0" value={form.position} onChange={(e) => setForm({ ...form, position: Number(e.target.value) })} /></label><label><span>Starts at</span><input type="datetime-local" value={form.startsAt} onChange={(e) => setForm({ ...form, startsAt: e.target.value })} /></label><label><span>Ends at</span><input type="datetime-local" value={form.endsAt} onChange={(e) => setForm({ ...form, endsAt: e.target.value })} /></label></div><label className="cms-enabled"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm({ ...form, enabled: e.target.checked })} />Publish this banner</label>{message && <p className="form-error" role="status">{message}</p>}<footer><button type="button" className="button" onClick={() => setForm(null)}>Cancel</button><button className="button button-dark" disabled={busy}>{busy ? "Saving…" : "Save banner"}</button></footer></form></section></div>}</>;
}
