"use client";
import { FormEvent, useState } from "react";
import { Building2, LoaderCircle, Pencil, Plus, Save, X } from "lucide-react";

export type SupplierView = { id: number; name: string; legalName: string | null; gstNumber: string | null; contactName: string | null; contactNumber: string | null; email: string | null; address: string; city: string; state: string; postalCode: string; isActive: boolean };
const empty = { name: "", legalName: "", gstNumber: "", contactName: "", contactNumber: "", email: "", address: "", city: "", state: "", postalCode: "", isActive: true };

export function SupplierManager({ initial }: { initial: SupplierView[] }) {
  const [suppliers, setSuppliers] = useState(initial); const [editing, setEditing] = useState<SupplierView | null>(null); const [adding, setAdding] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget); const data = Object.fromEntries(form); const payload = { ...data, isActive: form.has("isActive") }; const id = editing?.id; const response = await fetch(id ? `/api/admin/suppliers/${id}` : "/api/admin/suppliers", { method: id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); setBusy(false); if (!response.ok) return setMessage(result.error?.message || "Supplier could not be saved."); setSuppliers((current) => id ? current.map((item) => item.id === id ? result.supplier : item) : [...current, result.supplier].sort((a, b) => a.name.localeCompare(b.name))); setEditing(null); setAdding(false); }
  const active = editing ? { ...empty, ...editing } : empty;
  return <><header className="admin-top"><div><p className="eyebrow">Sourcing directory</p><h1>Suppliers</h1></div><button className="button button-dark" onClick={() => { setEditing(null); setAdding(true); }}><Plus size={16} />Add supplier</button></header><p className="settings-lead">Supplier legal and GST details are snapshotted when an order is placed and printed on its invoice.</p>
    {(adding || editing) && <form className="settings-section supplier-form" onSubmit={save}><div className="settings-section-head"><div><p className="eyebrow">{editing ? "Edit record" : "New record"}</p><h2>{editing ? editing.name : "Supplier details"}</h2></div><button type="button" className="admin-secondary" onClick={() => { setAdding(false); setEditing(null); }}><X size={15} />Close</button></div><div className="settings-fields two"><label className="settings-field"><span>Display name</span><input name="name" defaultValue={active.name} required /></label><label className="settings-field"><span>Legal name</span><input name="legalName" defaultValue={active.legalName ?? ""} /></label><label className="settings-field"><span>GST number</span><input name="gstNumber" defaultValue={active.gstNumber ?? ""} /></label><label className="settings-field"><span>Contact person</span><input name="contactName" defaultValue={active.contactName ?? ""} /></label><label className="settings-field"><span>Contact number</span><input name="contactNumber" defaultValue={active.contactNumber ?? ""} /></label><label className="settings-field"><span>Email</span><input name="email" type="email" defaultValue={active.email ?? ""} /></label><label className="settings-field full"><span>Address</span><textarea name="address" rows={3} defaultValue={active.address} required /></label><label className="settings-field"><span>City</span><input name="city" defaultValue={active.city} required /></label><label className="settings-field"><span>State</span><input name="state" defaultValue={active.state} required /></label><label className="settings-field"><span>PIN code</span><input name="postalCode" inputMode="numeric" defaultValue={active.postalCode} required /></label></div><label className="switch-row"><div><strong>Active supplier</strong><p>Available for assignment to products.</p></div><input type="checkbox" name="isActive" defaultChecked={active.isActive} /></label>{message && <p className="save-error">{message}</p>}<button className="button button-dark" disabled={busy}>{busy ? <LoaderCircle className="spin" size={16} /> : <Save size={16} />}{busy ? "Saving…" : "Save supplier"}</button></form>}
    <section className="supplier-grid">{suppliers.map((supplier) => <article className="settings-section" key={supplier.id}><div className="supplier-card-head"><Building2 /><span className={`visibility ${supplier.isActive ? "visible" : ""}`}>{supplier.isActive ? "Active" : "Inactive"}</span></div><h2>{supplier.name}</h2>{supplier.legalName && <p>{supplier.legalName}</p>}<dl><dt>GSTIN</dt><dd>{supplier.gstNumber || "Not provided"}</dd><dt>Address</dt><dd>{supplier.address}, {supplier.city}, {supplier.state} {supplier.postalCode}</dd><dt>Contact</dt><dd>{supplier.contactName || "—"}{supplier.contactNumber ? ` · ${supplier.contactNumber}` : ""}</dd></dl><button className="admin-secondary" onClick={() => { setAdding(false); setEditing(supplier); }}><Pencil size={15} />Edit</button></article>)}{!suppliers.length && <div className="admin-empty"><Building2 /><h2>No suppliers yet</h2><p>Add the legal seller that fulfils your products.</p></div>}</section></>;
}
