"use client";
import Image from "next/image";
import Link from "next/link";
import { Heart, ShoppingBag, Trash2 } from "lucide-react";
import { createContext, useCallback, useContext, useEffect, useState } from "react";
import { useCart } from "./cart";

type WishlistView = { id: number | null; count: number; items: { id: number; productId: number; variantId: number | null; available: boolean; canMoveToCart: boolean; moveVariantId: number | null; product: { name: string; slug: string; category: string; imageUrl: string | null; pricePaise: number }; variant: { sku: string; color: string; size: string; stockQuantity: number } | null }[] };
const empty: WishlistView = { id: null, count: 0, items: [] };
const WishlistContext = createContext<{ wishlist: WishlistView; authenticated: boolean; busy: boolean; message: string; toggle: (productId: number, variantId?: number | null) => Promise<void>; remove: (id: number) => Promise<void>; moved: (id: number) => void } | null>(null);
async function wishlistRequest(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); const body = await response.json(); if (!response.ok) throw Object.assign(new Error(body.error?.message ?? "Unable to update saved pieces."), { status: response.status }); return body as WishlistView & { authenticated?: boolean }; }
export function WishlistProvider({ children }: { children: React.ReactNode }) { const [wishlist, setWishlist] = useState(empty); const [authenticated, setAuthenticated] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); useEffect(() => { wishlistRequest("/api/wishlist").then((value) => { setWishlist(value); setAuthenticated(value.authenticated !== false); }).catch(() => undefined); }, []); const toggle = useCallback(async (productId: number, variantId?: number | null) => { if (!authenticated) { setMessage("Sign in to save pieces to your wishlist."); return; } setBusy(true); setMessage(""); try { const existing = wishlist.items.find((item) => item.productId === productId && item.variantId === (variantId ?? null)); setWishlist(await wishlistRequest(existing ? `/api/wishlist/${existing.id}` : "/api/wishlist", existing ? { method: "DELETE" } : { method: "POST", body: JSON.stringify({ productId, variantId: variantId ?? null }) })); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update saved pieces."); } finally { setBusy(false); } }, [authenticated, wishlist.items]); const remove = async (id: number) => { setBusy(true); try { setWishlist(await wishlistRequest(`/api/wishlist/${id}`, { method: "DELETE" })); } finally { setBusy(false); } }; const moved = (id: number) => setWishlist((value) => ({ ...value, items: value.items.filter((item) => item.id !== id), count: Math.max(0, value.count - 1) })); return <WishlistContext.Provider value={{ wishlist, authenticated, busy, message, toggle, remove, moved }}>{children}</WishlistContext.Provider>; }
export function useWishlist() { const value = useContext(WishlistContext); if (!value) throw new Error("useWishlist must be inside WishlistProvider"); return value; }
export function WishlistButton({ productId, variantId, name, className = "wish" }: { productId: number; variantId?: number | null; name: string; className?: string }) { const { wishlist, busy, message, toggle } = useWishlist(); const saved = wishlist.items.some((item) => item.productId === productId && item.variantId === (variantId ?? null)); return <><button type="button" className={`icon-button ${className} focus-ring`} disabled={busy} aria-label={`${saved ? "Remove" : "Add"} ${name} ${saved ? "from" : "to"} wishlist`} aria-pressed={saved} onClick={() => toggle(productId, variantId)}><Heart size={18} fill={saved ? "currentColor" : "none"} /></button>{message && !saved && <span className="wishlist-prompt">{message} <Link href="/login">Sign in</Link></span>}</>; }
const money = (paise: number) => `₹${(paise / 100).toLocaleString("en-IN")}`;
export function WishlistPageContent() { const { wishlist, authenticated, busy, message, remove, moved } = useWishlist(); const { add } = useCart(); if (!authenticated) return <div className="wishlist-loading">Loading your saved pieces…</div>; if (!wishlist.items.length) return <div className="wishlist-empty"><Heart /><h2>Your wishlist is ready for inspiration.</h2><p>Save pieces from the collection and they’ll appear here.</p><Link href="/shop" className="button button-dark">Explore the collection</Link></div>; return <>{message && <p className="cart-api-error">{message}</p>}<div className="wishlist-grid">{wishlist.items.map((item) => <article key={item.id} className="wishlist-card">{item.product.imageUrl ? <Image src={item.product.imageUrl} alt="" width={420} height={540} unoptimized /> : <span>{item.product.name.charAt(0)}</span>}<div><p className="eyebrow">{item.product.category}</p><h2><Link href={`/products/${item.product.slug}`}>{item.product.name}</Link></h2><p>{item.variant ? `${item.variant.color} / ${item.variant.size} · ${item.variant.sku}` : "Product saved — choose an available option when moving to bag"}</p><strong>{money(item.product.pricePaise)}</strong>{!item.available && <p className="wishlist-unavailable">Currently unavailable — kept here for you.</p>}<div className="wishlist-actions"><button disabled={busy || !item.canMoveToCart} className="button button-dark" onClick={async () => { if (item.moveVariantId && await add(item.moveVariantId, 1)) { await fetch(`/api/wishlist/${item.id}`, { method: "DELETE" }); moved(item.id); } }}><ShoppingBag size={15} />Move to bag</button><button disabled={busy} aria-label={`Remove ${item.product.name}`} onClick={() => remove(item.id)}><Trash2 size={15} /></button></div></div></article>)}</div></>; }
