import { BadgePercent, IndianRupee, PackageCheck, ReceiptIndianRupee, ShoppingBag, Star, TrendingDown, TrendingUp, UserPlus, Users } from "lucide-react";
import { analyticsData, analyticsPeriod, ANALYTICS_PERIODS } from "@/lib/analytics";

const money = (value: number) => `₹${(value / 100).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
const labelDate = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString("en-IN", { day: "numeric", month: "short" });
function Change({ value }: { value: number }) { const Icon = value >= 0 ? TrendingUp : TrendingDown; return <span className={`analytics-change ${value < 0 ? "negative" : ""}`}><Icon size={13} />{Math.abs(value)}% vs previous period</span>; }

export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ days?: string }> }) {
  const days = analyticsPeriod((await searchParams).days); const data = await analyticsData(days); const maxDaily = Math.max(1, ...data.daily.map((day) => day.revenuePaise)); const maxProduct = Math.max(1, ...data.topProducts.map((item) => item.revenuePaise)); const totalStatus = Math.max(1, data.statuses.reduce((sum, item) => sum + item.count, 0));
  const metrics = [[money(data.revenuePaise), "Paid revenue", IndianRupee, <Change key="revenue" value={data.revenueChange} />], [String(data.placedOrders), "Placed orders", ShoppingBag, <Change key="orders" value={data.orderChange} />], [money(data.averageOrderPaise), "Average paid order", ReceiptIndianRupee, <span key="paid">Paid orders only</span>], [String(data.unitsSold), "Units sold", PackageCheck, <span key="units">Paid, non-cancelled</span>]] as const;
  return <main className="admin-main analytics-page"><header className="admin-top"><div><p className="eyebrow">Performance intelligence</p><h1>Analytics</h1><p className="analytics-range">{data.start.toLocaleDateString("en-IN")} – {data.end.toLocaleDateString("en-IN")}</p></div><form className="analytics-period"><label>Reporting period<select name="days" defaultValue={days}>{ANALYTICS_PERIODS.map((period) => <option value={period} key={period}>Last {period} days</option>)}</select></label><button className="button button-dark">Apply</button></form></header>
    <section className="metric-grid analytics-metrics">{metrics.map(([value, label, Icon, note]) => <article className="metric" key={label}><span className="metric-icon"><Icon size={18} /></span><strong>{value}</strong><span>{label}</span><small>{note}</small></article>)}</section>
    <section className="analytics-chart-card"><div className="analytics-card-head"><div><p className="eyebrow">Collected sales</p><h2>Revenue over time</h2></div><strong>{money(data.revenuePaise)}</strong></div><div className="analytics-bars" style={{ minWidth: `${Math.max(700, data.daily.length * 18)}px` }}>{data.daily.map((day, index) => <div className="analytics-bar-column" key={day.date}><span className="analytics-bar" style={{ height: `${Math.max(day.revenuePaise ? 4 : 1, day.revenuePaise / maxDaily * 100)}%` }} title={`${labelDate(day.date)} · ${money(day.revenuePaise)} · ${day.orders} paid order(s)`} /><small>{(days <= 30 || index % Math.ceil(days / 12) === 0) ? labelDate(day.date) : ""}</small></div>)}</div></section>
    <section className="analytics-finance-grid"><article><BadgePercent /><span>Discounts given</span><strong>{money(data.discountsPaise)}</strong></article><article><PackageCheck /><span>Shipping collected</span><strong>{money(data.shippingPaise)}</strong></article><article><ReceiptIndianRupee /><span>Platform fees</span><strong>{money(data.platformFeesPaise)}</strong></article><article><IndianRupee /><span>GST included</span><strong>{money(data.taxIncludedPaise)}</strong></article></section>
    <section className="analytics-two-column"><article className="analytics-panel"><div className="analytics-card-head"><div><p className="eyebrow">Merchandising</p><h2>Top products</h2></div></div><div className="ranked-list">{data.topProducts.map((product, index) => <div key={product.name}><span className="rank">{index + 1}</span><div><b>{product.name}</b><small>{product.units} units</small><i><em style={{ width: `${product.revenuePaise / maxProduct * 100}%` }} /></i></div><strong>{money(product.revenuePaise)}</strong></div>)}{!data.topProducts.length && <p className="analytics-empty">No paid product sales in this period.</p>}</div></article><article className="analytics-panel"><div className="analytics-card-head"><div><p className="eyebrow">Catalogue mix</p><h2>Category performance</h2></div></div><div className="analytics-table"><div className="analytics-table-head"><span>Category</span><span>Units</span><span>Revenue</span></div>{data.topCategories.map((category) => <div key={category.name}><b>{category.name}</b><span>{category.units}</span><strong>{money(category.revenuePaise)}</strong></div>)}{!data.topCategories.length && <p className="analytics-empty">No category sales yet.</p>}</div></article></section>
    <section className="analytics-two-column"><article className="analytics-panel"><div className="analytics-card-head"><div><p className="eyebrow">Fulfilment</p><h2>Order status</h2></div></div><div className="status-analysis">{data.statuses.map((item) => <div key={item.status}><span>{item.status.replaceAll("_", " ")}</span><i><em style={{ width: `${item.count / totalStatus * 100}%` }} /></i><b>{item.count}</b></div>)}</div><div className="analytics-mini-metrics"><span><b>{data.deliveredOrders}</b> delivered</span><span><b>{data.cancelledOrders}</b> cancelled</span></div></article><article className="analytics-panel"><div className="analytics-card-head"><div><p className="eyebrow">Checkout preference</p><h2>Payment mix</h2></div></div><div className="payment-mix">{data.paymentMix.map((payment) => <div key={payment.method}><span>{payment.method === "COD" ? "Cash on Delivery" : "Razorpay / online"}</span><b>{payment.count} orders</b><strong>{money(payment.revenuePaise)} paid</strong></div>)}</div></article></section>
    <section className="analytics-insights"><article><UserPlus /><div><span>New customers</span><strong>{data.newCustomers}</strong><small>Registered in this period</small></div></article><article><Users /><div><span>Repeat purchasers</span><strong>{data.repeatCustomers}</strong><small>Placed 2+ orders in period</small></div></article><article><Star /><div><span>Approved reviews</span><strong>{data.approvedReviews}</strong><small>{data.approvedReviews ? `${data.averageRating.toFixed(1)} average rating` : "No new approved reviews"}</small></div></article><article><PackageCheck /><div><span>Stock retail value</span><strong>{money(data.inventoryRetailValuePaise)}</strong><small>Current active inventory</small></div></article></section>
    <p className="analytics-footnote">Revenue metrics include only paid, non-cancelled orders. GST is included in product prices and is not added again. Inventory value is an estimated retail value, not product cost or profit.</p>
  </main>;
}
