import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { Star } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { productInclude, calculateDiscountPercent } from "@/lib/products";
import { VariantPicker } from "@/components/variant-picker";
import { ProductCard } from "@/components/product-card";
import { WishlistButton } from "@/components/wishlist";

async function productBySlug(slug: string) { return prisma.product.findFirst({ where: { slug, status: "ACTIVE", archivedAt: null, category: { archivedAt: null, isVisible: true } }, include: productInclude }); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const product = await productBySlug((await params).slug); return product ? { title: product.seoTitle || product.name, description: product.seoDescription || product.shortDescription, alternates: { canonical: `/products/${product.slug}` }, openGraph: { title: product.seoTitle || product.name, description: product.seoDescription || product.shortDescription || undefined, images: product.images[0] ? [{ url: `/api/media/${product.images[0].media.id}`, alt: product.images[0].altText }] : [] } } : {}; }

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const product = await productBySlug((await params).slug); if (!product) notFound();
  const [related, reviews] = await Promise.all([
    prisma.product.findMany({ where: { id: { not: product.id }, categoryId: product.categoryId, status: "ACTIVE", archivedAt: null }, include: { category: true, images: { include: { media: true }, orderBy: { position: "asc" }, take: 1 } }, orderBy: { createdAt: "desc" }, take: 4 }),
    prisma.review.findMany({ where: { productId: product.id, status: "APPROVED" }, include: { user: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 50 })
  ]);
  const discount = calculateDiscountPercent(product.regularPricePaise, product.salePricePaise);
  const average = reviews.length ? reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length : 0;
  const jsonLd = { "@context": "https://schema.org", "@type": "Product", name: product.name, description: product.shortDescription, sku: product.skuReference, brand: product.brand ? { "@type": "Brand", name: product.brand } : undefined, image: product.images.map((image) => `/api/media/${image.media.id}`), aggregateRating: reviews.length ? { "@type": "AggregateRating", ratingValue: average.toFixed(1), reviewCount: reviews.length } : undefined, offers: { "@type": "Offer", priceCurrency: "INR", price: ((product.salePricePaise ?? product.regularPricePaise) / 100).toFixed(2), availability: product.variants.some((variant) => variant.isActive && variant.stockQuantity > 0) ? "https://schema.org/InStock" : "https://schema.org/OutOfStock", url: `/products/${product.slug}` } };

  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /><section className="container product-detail"><div className="product-gallery">{product.images.length ? product.images.map((image) => <div key={image.id}><Image src={`/api/media/${image.media.id}`} alt={image.altText} fill unoptimized priority={image.position === 0} sizes="(max-width: 800px) 100vw, 50vw" /></div>) : <div className="product-placeholder"><span>{product.name.charAt(0)}</span></div>}</div><div className="product-detail-copy"><p className="eyebrow">{product.category.name} · {product.gender.toLowerCase()}</p><div className="detail-title-row"><h1>{product.name}</h1><WishlistButton productId={product.id} name={product.name} className="detail-wish" /></div>{reviews.length > 0 && <a className="product-rating-summary" href="#reviews"><span><Star size={17} fill="currentColor" />{average.toFixed(1)}</span>{reviews.length} verified review{reviews.length === 1 ? "" : "s"}</a>}{discount > 0 && <span className="detail-discount">{discount}% off</span>}<p className="detail-short">{product.shortDescription}</p><VariantPicker variants={product.variants} regularPricePaise={product.regularPricePaise} salePricePaise={product.salePricePaise} /><div className="detail-description"><h2>Details</h2><p>{product.description || "A considered Yoranzify piece made for effortless everyday styling."}</p><p>GST: {Number(product.gstPercent)}% {product.hsnCode && `· HSN ${product.hsnCode}`}</p></div></div></section>
    <section className="container section product-reviews" id="reviews"><div className="section-head"><div><p className="eyebrow">Verified customers</p><h2 className="section-title">Ratings & reviews</h2></div>{reviews.length > 0 && <div className="review-average"><strong>{average.toFixed(1)}</strong><span><Star fill="currentColor" />Based on {reviews.length} review{reviews.length === 1 ? "" : "s"}</span></div>}</div>{reviews.length ? <div className="review-grid">{reviews.map((review) => <article key={review.id}><div className="review-stars-static">{[1,2,3,4,5].map((star) => <Star size={16} fill={star <= review.rating ? "currentColor" : "none"} key={star} />)}</div>{review.title && <h3>{review.title}</h3>}<p>{review.comment}</p><footer><b>{review.user.name.split(" ")[0]}</b><span>Verified purchase · {new Date(review.createdAt).toLocaleDateString("en-IN")}</span></footer></article>)}</div> : <div className="review-empty"><Star /><h3>No reviews yet</h3><p>Verified buyers can review this piece after delivery.</p></div>}</section>
    {related.length > 0 && <section className="container section related-products"><div className="section-head"><div><p className="eyebrow">Style it your way</p><h2 className="section-title">You may also like</h2></div></div><div className="product-grid">{related.map((item) => <ProductCard key={item.id} productId={item.id} name={item.name} meta={item.category.name} price={`₹${((item.salePricePaise ?? item.regularPricePaise) / 100).toLocaleString("en-IN")}`} href={`/products/${item.slug}`} imageUrl={item.images[0] ? `/api/media/${item.images[0].media.id}` : undefined} />)}</div></section>}
  </>;
}
